### ISSUE TITLE
Slide freezing frequently on the latest update

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#996] opened 2016-02-15 18:42 UTC
I have no way to reproduce it consistently, but often when I open the comments for a post, slide will hang up (but not crash), and I'll have to force it to quit and restart it

**Comment by ccrama** [comment] 2016-02-15 18:47
That should have been fixed with the last update, if you find a way to consistently reproduce it that would be great (first post works fine for me) :)

**Comment by kufii** [comment] 2016-02-15 18:55
it generally happens when I'm sliding through a bunch of posts and reading comments on all of them, wish I could give you more information but it seems pretty random

**Comment by LordManhattan** [comment] 2016-02-15 19:45
Just happened here, only it'll actually crash after a couple of seconds. It'll freeze for 10-15 seconds, and then it'll crash. 

02-15 20:39:25.664 E/ActivityManager(1131): ANR in me.ccrama.redditslide (me.ccrama.redditslide/.Activities.CommentsScreen)

**Comment by ccrama** [comment] 2016-02-15 20:15
Spoilers are working, you have to click the text next to it that says spoiler :). And I think I fixed the bug and made it actually crash the all, the big in question told the app to do nothing if it was supposed to crash. I haven't had an issue since fixing it so let's hope that was the problem!

**Comment by ccrama** [comment] 2016-02-15 20:24
Found and fixing the comment crash issue as well

**Comment by LordManhattan** [comment] 2016-02-15 20:35
Nope, spoilers don't work here: https://vid.me/3xJ4

Running 4.6.0.38-a72df68-dirty

**Comment by ccrama** [comment] 2016-02-15 23:42
Fixed @LordManhattan and fixed the freezes too!

**Closed by ccrama** 2016-02-15 23:42 UTC
Labels: bug, needs verification
