### ISSUE TITLE
Weird behaviour when selecting posts

### ISSUE THREAD

**Issue by 2fst4u** [ccrama/Slide#1600] opened 2016-04-27 23:30 UTC
Slide version: 5.3.2.4
Android version: 6.0.1

On a very regular basis when I attempt to select a post within a single sub, I am taken to the lost that is directly below it. Once this occurs it continues to happen for every post still visible in the sub and the only way to fix it is to force close the app.

To explain further, I will be browsing posts (let's call them A, B, C, D...) And want to open post B. On clicking B I am taken to post C. Once this phenomena occurs, backing out and trying again does the same thing, and from now on clicking any post takes me to the next one (post D now takes me to E, post E now takes me to F).

Edit: this behaviour extends to the individual hide action also. The first few posts works fine then when I go to hide a post the one below it disappears and not the post I actually clicked "hide" on.

**Comment by Nxt3** [comment] 2016-04-28 00:56
I can vouch for this happening to me from time to time.

**Comment by ccrama** [comment] 2016-04-28 14:07
Do you have any more details? I've never run into this issue and would like to reproduce

**Comment by Nxt3** [comment] 2016-04-28 15:09
It almost seemed like that bug where if you hid a post, then selected a post past that point--it would be one off from the actual post you selected; only--I don't think I have to hide a post for this to happen. If it occurs again, I'll let you know. Now that I think of it, it hasn't happened since builds from yesterday though--so maybe it's fixed?

**Comment by ccrama** [comment] 2016-04-28 18:46
Believe it's fixed now, I wasn't saving the result of the hide so opening posts after hide would always be the wrong position!

**Closed by ccrama** 2016-04-28 18:46 UTC
Labels: bug, priority: low
