### ISSUE TITLE
Able to open post / close keyboard while keeping subreddit list open

### ISSUE THREAD

**Issue by matty1086** [ccrama/Slide#1951] opened 2016-07-21 00:19 UTC
Hard to explain this one, but can reproduce 100% of the time.

Repro steps:
Open app
Long press on "Frontpage" in the title to bring up the subreddit list
Tap on a post that's in the background
Post loads
Now press down arrow to close the keyboard
The window with the subreddits still appears with no way to close it (See screenshot)

The only way to close this is to swipe back to the main list
Tap in the search list
Tap the X to close the search

or

Turn off the screen / turn on again

Expected result: If i tap on a post, the search / keyboard should close 
If i close the keyboard the search should likely close as well

Alternatively, don't allow tapping on posts while search / subreddit list is open

Screenshot:
![screenshot_20160720-171524](https://cloud.githubusercontent.com/assets/17831198/17007476/e9a2e53c-4e9d-11e6-861d-f3c04b6f5891.png)

Slide version: 5.4 Alpha 2
Android version: N DP4

**Comment by Nxt3** [comment] 2016-07-21 03:46
This seems to be an Android N issue. I can't reproduce this.

**Comment by matty1086** [comment] 2016-07-21 03:51
Yep, does appear N only. Just tried on my Nexus 7 still on 6.0.1 and do not have the issue. Thanks!

**Comment by Nxt3** [comment] 2016-07-21 04:16
There seem to be several keyboard related Nougat issues. Hopefully they are fixed in the final release.

**Comment by ccrama** [comment] 2016-07-21 04:39
Don't know if there is much we can do on our end

**Comment by ccrama** [comment] 2016-08-01 13:42
Merging with #1984

**Closed by ccrama** 2016-08-01 13:42 UTC
Labels: bug, not pursuing
