### ISSUE TITLE
Auto correct doesn't work in "title" field when creating a new post

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide#2798] opened 2018-05-30 16:30 UTC
Slide 5.8.6
S9+ TouchWiz Oreo, 2/1/18 patch level

![](https://i.imgur.com/gPU7Tt9.jpg) 

Basically, it gives autocorrect suggestions but instead of replacing the words, just leaves it as is.  The bold on the word you see on my suggestion bar never appears when typing in the title field.

**Comment by Tensounder54** [comment] 2018-11-13 16:49
This issue is resolved in a later version of Slide and needs to be closed.

**Comment by ryder55** [comment] 2018-11-13 17:42
hi, can you please provide me link to an issue where this is fixed? when i tried it two weeks ago it wasnt working.

**Comment by Tensounder54** [comment] 2018-11-14 10:42
The issue is resolved in Slide version 5.9-alpha2. Although it appears that your PR was merged so...

**Comment by Tensounder54** [comment] 2019-01-27 19:38
Issue resolved in PR #2884

**Closed by Tensounder54** 2019-01-27 19:38 UTC
Labels: Bug
