### ISSUE TITLE
Blank space appears in comments with code only content.

### ISSUE THREAD

**Issue by piyush-rvc** [ccrama/Slide#1719] opened 2016-05-09 10:43 UTC
Slide version:5.3.4
Android version:5.1.1

Initial two lines are blank if the comment contains only code.

**Comment by ccrama** [comment] 2016-05-09 15:48
Thanks for the report! Duplicate of #1514

**Closed by ccrama** 2016-05-09 15:48 UTC
Labels: bug, cosmetic

**Comment by piyush-rvc** [comment] 2016-05-10 05:25
@ccrama  I would like to fix it, where should I look into. It seems processing for comment containing code happens some where in addition to commentAdapter, which is causing the issue. Thanks!!

**Comment by piyush-rvc** [comment] 2016-05-10 06:30
@ccrama  also, why is comment display as firstTextView and CommentOverflow? IMO, using only CommentOverflow would do the job.

**Comment by ccrama** [comment] 2016-05-10 16:38
@piyush-rvc  thank you! And it's like that because we don't have to re-inflate a new first textview every time the view is displayed, which makes it much faster. The CommentOverflow is only touched when needed, which makes scrolling much faster
