### ISSUE TITLE
Not showing newly subscribed subreddits

### ISSUE THREAD

**Issue by fangorntheent** [ccrama/Slide#459] opened 2015-11-08 21:16 UTC
Latest version of slide.
Newly subscribed subreddits aren't showing as being subscribed in app (not in sidebar or tabs). I subbed to it a day ago and have opened and closed slide at least ten times since then.

**Comment by l3d00m** [comment] 2015-11-25 08:18
Marking this high priority because it confuses users. Even if I'm subscribing through the website, it's not showing up after a day in Slide.

**Comment by fangorntheent** [comment] 2015-11-25 08:55
It's a problem with needing permission to join said subreddit.  /r/ravenclaw
You can't just subscribe. Normal Subreddits show up fairly reasonably quickly.

**Comment by l3d00m** [comment] 2015-11-25 09:02
No, it's not. This is an issue too, but normal Subreddits aren't showing up sometimes too.

**Comment by fangorntheent** [comment] 2015-11-25 09:03
Oh. My bad. /r/ravenclaw still doesn't show in my subs, by the way.

**Comment by l3d00m** [comment] 2015-11-25 09:18
No problem! Yeah, #498 is the issue you meant.

**Comment by ccrama** [comment] 2015-12-04 14:45
Wait, you have to go into the sidebar, profile, and click "Sync Subreddits". Not a bug :P

**Comment by l3d00m** [comment] 2015-12-04 14:51
Doesn't work, even when I restarted after it. It will show up after a few days only.

**Comment by ccrama** [comment] 2015-12-04 14:54
Works for me every time :(. If you are closing the app right afterwards, Android won't let the .apply() on the SharedPreferences save as it's scheduled for the future

**Comment by okungnyo** [comment] 2015-12-04 15:38
The user shouldn't HAVE to go into the sidebar, profile, and click "Sync Subreddits" though, right?

Shouldn't it be automatic?

**Comment by ccrama** [comment] 2015-12-04 15:39
Every other app does it this way, and that allowed me to shave 5 seconds off the loading time

**Comment by okungnyo** [comment] 2015-12-04 15:40
OK if it results in faster load times, then I'm all for it.

**Comment by fangorntheent** [comment] 2015-12-04 16:31
Doesn't work for /r/ravenclaw

**Comment by l3d00m** [comment] 2015-12-04 17:21
That's because it's private, there's another issue for that.

**Closed** 2015-12-04 18:39 UTC
Labels: bug, high priority
