### ISSUE TITLE
Android N Issues

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1206] opened 2016-03-19 04:21 UTC
Android version: N preview
I can't reveal spoilers on the latest update

**Comment by ccrama** [comment] 2016-03-19 04:24
Long press on the spoiler link. What kind of spoiler is it? More than likely, it's a spoiler tag we haven't supported yet

**Comment by kufii** [comment] 2016-03-19 04:29
No it's the /s one, it was working in the pervious versions.

It displays properly, I just can't reveal it

Long pressing the link just triggers the collapse comment thread

**Comment by ccrama** [comment] 2016-03-19 04:31
What does clicking it do? The code hasn't changed since v4.5 so it probably isn't something new in the update

**Comment by kufii** [comment] 2016-03-19 04:39
Maybe it's an Android N issue then? Clicking it does nothing at all

**Comment by kufii** [comment] 2016-03-19 04:47
Yeah, seems to be working fine on my marshmallow tablet

**Comment by Alexendoo** [comment] 2016-03-19 11:50
Seems links are just generally messed up on N

**Comment by ccrama** [comment] 2016-03-19 15:36
N is screwing up a lot of stuff, and I don't have an N compatible device to test on :(. Hopefully someone with an N device can make a PR to fix it

**Comment by ccrama** [comment] 2016-03-19 15:40
Appears to affect settings restore and comment link opening as well

**Comment by kufii** [comment] 2016-03-19 15:49
the settings restore issue isn't an Android N issue. The issue occurred on a tablet running Marshmallow

**Comment by ccrama** [comment] 2016-03-19 15:57
I can't reproduce it, but I'll look into it!

**Comment by kufii** [comment] 2016-03-19 16:01
it's possible the issue has more to do with backing up than restoring, backing up isn't working properly for me

**Comment by kufii** [comment] 2016-03-19 17:29
I don't know how helpful this is, but I downloaded the project and tried debugging it. onTouchEvent in TextViewLinkHandler is never being run

**Comment by ccrama** [comment] 2016-03-22 15:20
For the link issue, what comment settings do you have turned on?

**Comment by kufii** [comment] 2016-03-22 15:30
When I was debugging I was using the default settings and was having the same issues

**Comment by ccrama** [comment] 2016-04-15 19:04
Link bug has been confirmed fixed in the N preview 2!

**Closed by ccrama** 2016-04-15 19:04 UTC
Labels: bug, priority: low
