### ISSUE TITLE
Request for ability to disable never ending scrolling

### ISSUE THREAD

**Issue by yaomtc** [ccrama/Slide#2401] opened 2017-03-30 13:31 UTC
Slide version: 5.5.4
Android version: 7.1.1

I'd like the ability to turn off endless scrolling, please!

**Comment by ccrama** [comment] 2017-04-07 16:57
Duplicate of #2260

**Closed by ccrama** 2017-04-07 16:57 UTC

**Comment by yaomtc** [comment] 2017-04-07 19:21
Oops, missed that. Thanks.
