### ISSUE TITLE
Weird behaviour/layout on post screen

### ISSUE THREAD

**Issue by HexParanoia** [ccrama/Slide#804] opened 2016-01-15 11:21 UTC
The username and points look off.

http://imgur.com/2LSyQ7e

**Comment by l3d00m** [comment] 2016-01-15 12:19
Duplicate of #415. Thanks for the report though. 

We haven't found out why it's occuring and it's occuring really rare for me too. That's why it isn't fixed yet.

**Closed by l3d00m** 2016-01-15 12:19 UTC
