### ISSUE TITLE
GIFs from redgifs.com are not recognized

### ISSUE THREAD

**Issue by rEnr3n** [ccrama/Slide#3165] opened 2020-05-13 02:04 UTC
Slide version: 6.3
Android version: 6.0.1

Redgifs links should be recognized as GIF instead of a link.

Example: **NSFW** https://www.reddit.com/r/redgifs/comments/gfvw9v/redgifs_links_on_reddit_see_comment/

**Comment by paulpark03** [comment] 2020-05-17 06:23
Duplicate of #3169 
Sorry. I didn't check this before I created a new pull request.

**Comment by MetalNeo** [comment] 2020-11-13 16:02
After updating to 6.6, redgifs gifs are not being recognized again.

**Comment by MetalNeo** [comment] 2020-11-15 12:50
False alarm. The WiFi network I normally use started blocking redgifs the same time I updated. Issue can be closed.

**Closed** 2020-11-15 12:53 UTC
Labels: Feature Request
