### ISSUE TITLE
Crash on nonexistent sub

### ISSUE THREAD

**Issue by kelvinalfaro** [ccrama/Slide#308] opened 2015-10-29 21:11 UTC
crash upon not finding the sub

Debug info:
 OS Version: 3.4.42-gb476356(4)
 OS API Level: 22
 Device: ghost
 Model (and Product): XT1053 (ghost_retail)
 RELEASE: 5.1
 BRAND: motorola
 DISPLAY: LPA23.12-15.5
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: motorola

Stacktrace: 

```
java.lang.NullPointerException: Attempt to invoke interface method 'com.google.android.gms.common.api.PendingResult com.google.android.gms.drive.DriveFolder.listChildren(com.google.android.gms.common.api.GoogleApiClient)' on a null object reference
	at me.ccrama.redditslide.Activities.SettingsBackup$2.onClick(SettingsBackup.java:188)
	at android.view.View.performClick(View.java:4785)
	at android.view.View$PerformClick.run(View.java:19884)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by Alexendoo** [comment] 2015-10-29 21:15
Can you remember what the subreddit name was or where the link was?

**Comment by ccrama** [comment] 2015-10-29 21:49
It looks like you clicked settings and then backup settings. It's crashing on code only within settings

**Comment by ccrama** [comment] 2015-11-05 05:50
Whelp closing this because can't reproduce

**Closed by ccrama** 2015-11-05 05:50 UTC
Labels: autoreport
