### ISSUE TITLE
link to Imgur tries to load in media viewer

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2185] opened 2016-09-22 17:45 UTC
https://reddit.com/r/BlackPeopleTwitter/comments/53zfqy/gotta_do_what_you_can_to_survive_out_here/d7xj58b?context=3

Click on "Imgur" in that comment. It's a direct link to Imgur. Should open in browser or Imgur app

**Comment by ccrama** [comment] 2016-09-22 18:36
I don't know if there is a way around that except for explicitly looking for only "imgur.com" and opening that in browser

**Comment by ccrama** [comment] 2016-09-24 20:04
I think this is closeable, don't know if there is a way to get intended behavior out of this

**Comment by Nxt3** [comment] 2016-09-27 00:05
I'll keep this open and investigate when I have time. :)

**Comment by fbis251** [comment] 2016-09-27 05:21
My album parser library can help you out with Imgur URL validation.

[Validation code](https://github.com/fbis251/album_parser/blob/113ce5358e5847a9ec4239c4811ce260e7348f24/lib/src/main/java/com/fernandobarillas/albumparser/imgur/ImgurParser.java#L70-L111)

[Tests for the validation code](https://github.com/fbis251/album_parser/blob/113ce5358e5847a9ec4239c4811ce260e7348f24/lib/src/test/java/com/fernandobarillas/albumparser/parser/ImgurParserTest.java#L91-L213)

**Comment by Tensounder54** [comment] 2018-11-09 15:39
This issue is resolved in a later verstion of slide and needs to be closed.

**Closed** 2018-12-04 13:43 UTC
Labels: bug
