### ISSUE TITLE
Typing in the subreddit search bar is glitchy

### ISSUE THREAD

**Issue by yasmara** [ccrama/Slide#1144] opened 2016-03-05 20:37 UTC
Slide version: 4.6.2
Android version: 6.0.1 & 6.0

It misses random letters and deselects itself unless you type really really slow

**Comment by Alexendoo** [comment] 2016-03-06 17:23
Fixed with 6504ec844eac4cd562d2f9b1b5d0e58eec57af4d

**Comment by septemus** [comment] 2016-04-08 22:24
https://drive.google.com/open?id=0B-2xpDNqB2krdmFZWExJVkh4eGM
Video of it in action.
Running 5.1.0, Android 6.0.1

**Comment by ccrama** [comment] 2016-04-14 21:27
Should be fixed now

**Comment by Nxt3** [comment] 2016-04-15 05:57
Not fixed when backspacing. Will post video in the morning

**Comment by septemus** [comment] 2016-04-15 15:05
In one of the newer updates, it has reappeared.

**Comment by Nxt3** [comment] 2016-04-15 15:07
[Dropbox video link of issue](https://www.dropbox.com/s/3srv99vx2yo0nok/2016_04_15_01_52_46_trim_00-00_00-18.mp4?dl=0)

**Comment by ccrama** [comment] 2016-04-15 17:55
I didn't change anything, so either the fix or the recurrence is placebo

**Comment by Nxt3** [comment] 2016-04-15 18:00
I think the fix worked if you're typing--but if you backspace, the issue is present.

**Comment by Alexendoo** [comment] 2016-04-15 21:18
It also seems to add entries if you backspace them http://i.imgur.com/27IYuwm.png

**Comment by ccrama** [comment] 2016-04-21 19:28
Is this still an issue?

**Comment by Nxt3** [comment] 2016-04-21 19:59
Yep. It happens more on my Pixel C than on my phone; and that's for both typing and deleting text.

**Comment by ccrama** [comment] 2016-05-03 04:20
I made the animation scrolling to the top faster, which was the cause of losing focus (typing while it's scrolling). Not a complete fix but the best we can do

**Closed by ccrama** 2016-05-03 04:20 UTC
Labels: bug, priority: high

**Comment by Alexendoo** [comment] 2016-05-03 10:39
Managed to narrow it down further to it being that the dataset was being invalidated during scroll, changed it to just notify changed (ca299261782af41dae3f2b8ef06e1c7c79a2b356) and it seems to work great
