### ISSUE TITLE
Nav drawer does not go under status bar

### ISSUE THREAD

**Issue by vemacs** [ccrama/Slide#408] opened 2015-11-07 16:43 UTC
Material design spec states that the nav drawer should go under the status bar (GMail, Google Play My Apps page, Reddit Sync). Slide does not do this. 

http://stackoverflow.com/questions/26913770/make-navigation-drawer-draw-behind-status-bar

**Comment by ccrama** [comment] 2016-05-11 15:35
This is basically a duplicate of #34 , merging with that for now

**Closed by ccrama** 2016-05-11 15:35 UTC
Labels: cosmetic, priority: low
