### ISSUE TITLE
Save picture behavior

### ISSUE THREAD

**Issue by plumbe0** [ccrama/Slide#568] opened 2015-11-17 20:01 UTC
When you tap on the diskette icon to save a picture you get no feedback, as the icon isn't doing anything (no circle animation), but the picture is actually saved. Also, saving a picture issues a Slide notification that does nothing and can only be swiped away. Shouldn't it be handled by the download manager like most apps do when downloading content?

**Comment by l3d00m** [comment] 2015-11-21 10:55
Dupe of #398

**Closed** 2015-11-21 10:55 UTC
Labels: bug
