### ISSUE TITLE
Rotating screen twice returns to the top of the list

### ISSUE THREAD

**Issue by trentusus** [ccrama/Slide#748] opened 2016-01-09 09:26 UTC
When scrolling through a list of posts, starting in portrait mode. Rotating to landscape maintains the position in the list. Rotating back to portrait returns you to the top of the list. Should the position be maintained?

**Comment by l3d00m** [comment] 2016-01-12 20:08
Which Slide version are you using? I cannot reproduce it on the alpha

**Comment by trentusus** [comment] 2016-01-12 20:22
4.5
Only happens on posts. Not in comments.

**Comment by hary585** [comment] 2016-01-13 19:50
I tried it, no issues for me.

**Comment by l3d00m** [comment] 2016-01-13 20:59
Same for me and some other guys on the IRC.

**Comment by ccrama** [comment] 2016-01-13 21:00
No issue for me either :(

**Comment by trentusus** [comment] 2016-01-13 22:29
How strange... I just reinstalled and it still happens when I rotate twice
on the front page list. Must be just me :/

**Comment by ccrama** [comment] 2016-01-13 22:31
A lot of that is handled by your OS, so might just be a device specific issue. What phone do you have?

**Comment by trentusus** [comment] 2016-01-13 22:46
HTC One M8
Running Android 6

**Comment by Korpip** [comment] 2016-01-13 22:47
I was able to reproduce on both my Nexus 7 2013(flo) and Moto X Play (lux) both running M.
In this video you will also see an image distortion bug in the image thumbnails after rotation.
The distorted images only happens on my Moto X Play which leads me to think that this bug is not one with Slide but more of a device thing that Slide might have to work around.
vid.me/eFFQ

**Comment by comprocket** [comment] 2016-02-02 03:25
Reproduced on my Nexus 6 running 6.0.1. Slide 4.5.1

**Comment by amweiss** [comment] 2016-02-13 13:07
Reproduced on my Nexus 5x running 6.0.1 with Slide 4.5.1

**Comment by l3d00m** [comment] 2016-02-13 13:18
Looks like a marshmallow issue.

**Comment by ccrama** [comment] 2016-02-13 15:57
Ooh, if it's just marshmallow, this is a bug with Google's RecyclerView and not Slide. Interesting! I'm waiting for marshmallow on my priv atm :(

**Comment by Plastix** [comment] 2016-02-13 16:08
I cannot replicate this issue running on my Nexus 5 running 6.0.1 with Slide 4.5.1

**Comment by amweiss** [comment] 2016-02-13 23:44
Probably doesn't help, but this doesn't happen in sync.

**Comment by ccrama** [comment] 2016-02-13 23:44
@amweiss  No it doesn't help

**Comment by amweiss** [comment] 2016-02-13 23:59
Well this should help:
It doesn't happen in slide while viewing comments, only posts with card mode disabled.

**Comment by amweiss** [comment] 2016-02-18 01:02
As of 4.6.0-83-e62230c it happens in card mode for posts now as well.

**Comment by amweiss** [comment] 2016-02-18 16:49
Now seems fixed in 4.6.0-89-4a4143c.

**Comment by trentusus** [comment] 2016-02-24 00:18
I also confirm this is fixed on my device. Thanks!

**Comment by ccrama** [comment] 2016-02-24 02:03
Woo!

**Closed by ccrama** 2016-02-24 02:03 UTC
Labels: bug
