### ISSUE TITLE
Hamburger animation is not disabled when opening nav drawer

### ISSUE THREAD

**Issue by vemacs** [ccrama/Slide#407] opened 2015-11-07 16:43 UTC
Material design spec states that the hamburger to arrow animation in the top left corner should be disabled when a nav drawer is opened (GMail, Reddit Sync, My Apps on Play Store). Slide still has it enabled.

**Comment by l3d00m** [comment] 2015-11-07 16:43
duplicate of #350, thanks for the report though

**Closed by l3d00m** 2015-11-07 16:43 UTC
