### ISSUE TITLE
Slide fails to load new reddit messages / comments - requires task kill to fix

### ISSUE THREAD

**Issue by bantar** [ccrama/Slide#1340] opened 2016-04-08 14:30 UTC
Slide version:   5.1.0
Android version:  5.0 Galaxy S5

This is a new issue that I'm seeing.  I don't yet have a pattern, but I have a guess at the failure cause.

tl;dr:  slide stops loading new messages or comments.  click on the options button and select discover.  Then say yes when it asks to reconnect.  Or task kill the app and restart.

Issue:  Slide operates normally for all functions, EXCEPT, for loading message comments and new messages from reddit.   From the main screen, if I see a message, I can click on it.  Comments will fail to load.  The message opens up normally, but we see a spinning circle.   If I click on the link or picture, it correctly loads that image or URL.  Same is true if I click on image or URL directly from main view.   If I slide to a new subreddit or use the goto function, the app will not load any message.   Just get the spinning circle.  If I go to my profile, I get an error message:  "Reddit user could not be retrieved".  If I click on the Discover button, it says:  "Reddit refused a request.   Would you like to attempt a re-connect to Reddit?"   Yes/No?    I clicked on Yes, waited at least 75 seconds, but nothing happened.  Next, I clicked on goto subreddit to see if this actually fixed anything and lo and behold, I'm reconnected.   Everything is back to normal now.

While writing this bug report, I've accidentally found this reconnect option.  However, the only way prior was to kill the app and restart it.  On the slide subreddit, I see another person reporting "Trouble Loading and Refreshing".   These might be related.

Here is my guess:   /r/all times out after a period of inactivity and you need to refresh.  I think somehow, this is at the root of the issue.   So far when I've seen this (I think), I was in /r/all and put the phone down for something and then returned much later, continuing where I left off.  For my last failure, I had a long thread opened and was part way thru it when I put the phone down.  Picked it back up and started reading again, in the same thread.  Then when I moved back to goto a new message it was no longer working.    THIS IS PURELY SPECULATION on my part.  I've seen this 3-4 times, but have not figured out the pattern.  This speculation is based strictly on my last failure.

**Comment by ccrama** [comment] 2016-04-08 14:39
This was fixed in 5.1.1, the issue is I told it to authenticate twice on the first start and never after that, even though it should have authenticated once on first start and once every time the token is expired.

**Closed** 2016-04-08 14:39 UTC
