### ISSUE TITLE
H to V image rotation resets position in Main View

### ISSUE THREAD

**Issue by bantar** [ccrama/Slide#1196] opened 2016-03-15 03:06 UTC
Slide version: 4.7.3
Android version: 5.0

Similar to issue #1067, but I think this is actually a different issue.

In /r/all at any position in the main list (sorted Hot).   In the main list, Rotate phone to H.  View image.  While viewing, rotate phone back to V.  Back out of the picture and find the position in the main view lost.  It resets back to the top of the list.

Note:  This does not fail if the image is viewed from the Vertical position first.   e.g.   In main list, rotated V, click on picture.  Rotate H, then back out.   No problem.

I can recreate this issue with multiple images, but here are 2 chosen at random:
https://www.reddit.com/r/pics/comments/4aeecr/body_scans_of_women_at_250_and_120_pounds/
https://www.reddit.com/r/pics/comments/4af54j/i_am_the_terror_that_flaps_in_the_night/

**Comment by ccrama** [comment] 2016-03-15 04:48
Does this occur without opening the image?

**Comment by bantar** [comment] 2016-03-15 04:51
Just a Galaxy S5, so no room for multi-column.   No, it does not occur without opening the image.  Screen rotation before opening the image never causes this problem.

**Comment by ccrama** [comment] 2016-03-15 04:52
Do you have Pro? It uses a different adapter if so, could be the issue

**Comment by bantar** [comment] 2016-03-15 04:53
No, I'm not using Pro.  Also, I just checked to see what GIFS would do.  They fail exactly as the static images I chose above.   One must follow the steps carefully to fail.

**Comment by ccrama** [comment] 2016-03-15 04:56
Hrm, cannot reproduce it with images, gifs, or albums. I'll see if anyone else can reproduce it

**Comment by bantar** [comment] 2016-03-15 05:06
I can consistently reproduce this issue.   Almost any image will work for me.   The samples are not really important for this bug.

**Comment by ccrama** [comment] 2016-03-15 17:06
I need someone else to reproduce it so we can rule out your device, OS, or other external factors

**Comment by raazman** [comment] 2016-03-15 18:36
Nexus 6P. Cannot reproduce.

**Comment by bantar** [comment] 2016-03-15 22:25
BTW, I'm using a Galaxy S5 with 2560x1440 resolution.    To reproduce, I follow the steps in the OP exactly.   Note:  After the step where the phone is rotated from H back to V with the picture still showing, I can see that the main subreddit list of posts in the background has already reset its position to the top image.

**Comment by ccrama** [comment] 2016-03-15 22:27
Can't reproduce on a Blackberry Priv, Nexus 5, or LG G4 (my family's phones). Let's see if anyone else can get it to break :(

**Comment by bantar** [comment] 2016-03-15 22:38
Since I'm the only one that can currently reproduce this, I did a bit more testing to see if it was related to sort order or if it was due to being in /r/all.  It appears to not be related to the subreddit or the specific picture.  Any subreddit fails and any picture fails.

I just tried a random subreddit (/r/mechanicadvice) and sorted by New.   I scrolled down about 10 messages to the first picture I found, followed the steps and when I hit back, I'm at the top of the subreddit.   My position was lost.     

Let me know if there are any specific tests that would be useful beyond this and I'll try them.

**Comment by ccrama** [comment] 2016-03-15 22:40
Try resetting app data and testing that, if it's a setting it should get fixed this way

**Comment by bantar** [comment] 2016-03-15 22:47
OK.  I reset the app data.  I cleared the cache.   I started reddit and Added my account and logged in.   I have not changed any settings.   Went back an retried the /r/mechanicadvice picture.  Failed identically.

**Comment by ccrama** [comment] 2016-03-19 21:00
Unless someone else has this bug or we can find a direct cause, I don't know what I can do unfortunately :(

**Comment by bantar** [comment] 2016-03-21 00:38
Unfortunately, this bug makes slide completely unusable.   After losing your place a few times, one gets tired of scrolling down 100's of messages to find your location.    I've attached a video showing the problem.   

Works Correctly:
https://gfycat.com/FineAgedGrassspider    Start at top, scroll to imgur image, click on image while V, then rotate H, then back out.   Still in same position.

Fails:
https://gfycat.com/FamousHideousGeese    Start at top, scroll to imgur image, Rotate H, click on image while H, then rotate V, then back out.   Notice, the position has returned to the top of the list.

**Comment by ccrama** [comment] 2016-03-21 00:41
I see that it's failing but unless someone else can reproduce it successfully, I don't really know where to start or what the issue could be

**Comment by bantar** [comment] 2016-03-21 01:12
OK, so I took my wife's S5, which has never installed slide, nor ever browsed reddit.  Clean install, did not create an account.   Verified that this device is failing identically.

NOTE:   These steps to recreate the problem are just that.  I don't purposely try to make it fail.  When I'm viewing reddit threads, picture have varied rotations.  I simply rotate as needed while going about my business and eventually find myself back at the top of the list.    It took me a while to get these steps precise.

**Comment by ccrama** [comment] 2016-03-21 03:04
Alright thank you for the information! That would be interesting to see if the s5 fails for others as well, it's confirmed working on nexus devices, s6 and above, and lg devices, so I wonder if it's specific to the s5

**Comment by bantar** [comment] 2016-03-28 18:46
Here's an update after using Slide v5 for a while.   I am noticing a few new things, but the problem largely remains...

New behavior:   dropping the phone (causing a rotation), and other previous non failing cases seem to make this problem occur.   I don't have a new pattern to report just yet.   The net effect is that I see it more often.   

New behavior:   on some images, I now see a strange "self-correction".   If I test the same image over and over again, 3+ times, it will sometimes fix itself and then no longer fail.   The initial 2-4 times, it would fail consistently, then work consistently.  Each time it fails, I'm back at the top of the list and scrolling back to the message.   HOWEVER, for a handful of images, they never stop failing.  It now seems that more images self-correct than never correct.   (I know it's crazy, but I'm just reporting what I see).

Vertical orientation consistency.   I can report that under well controlled situations, if I always maintain a vertical orientation when starting to view an image, it does not fail.   I can rotate it H after viewing it, and be OK.   This is just saying that if I'm very careful not to use the steps that fail, it works flawlessly.  Whatever the failure is, it's related to orientation.

**Comment by bantar** [comment] 2016-03-29 01:23
OK, I mentioned that Slide 5.0 seems to have made it easier to recreate this failure, but didn't yet know the pattern (e.g. dropping phone).   Here's a video of the new behavior.  The recorder switches orientation before it shows the screen change.   It somewhat appears to be two rotations, but it is just one.   I'll give you a play by play as well.  In a nutshell, the new behavior only requires that I enter the comments view.  There is no need to click on the image starting with v5.   In the previous version, this test case did not fail.    https://vid.me/oG3l

Start at the top of the subreddit. View is V.  Scroll down to a specific thread.  Click on the thread.  Rotate view to H.   Hit the back button.   NOTE:  At this point, we are looking at our starting position in the main view.   All is good at this point.   Now, rotate view back to V and watch the position jump back to the top of the subreddit.

**Comment by bantar** [comment] 2016-03-30 04:58
Well, I've managed to simplify the steps required for the new failure mode.   See this video:  https://vid.me/juGt  (Again, the recorder rotates itself before showing the screen rotation - this appears to be two steps, but is indeed a single event).   This is in /all with Hot.    

Starting at the top of the main view.   Scroll down a bit to load a few messages.   Rotate V -> H -> V.  Nothing happens.   Do it again.  V -> H -> V.  Nothing happens.   Now, scroll down to load a few more messages.   Rotate V -> H.   All is good.   Now rotate back to V and it jumps back to the top.

Simplified, rotate, scroll down enough then rotate again and the list position is reset.   The steps shown above showed 2 initial rotations to show that rotation alone is not the failure.  The failure is Rotate, then Load more messages, then Rotate again.    For instance, if I perform the steps, but only scroll a little, it will not fail.   It takes about 5-10 messages of scrolling to (which I'm guessing initiates a page read cycle) get it to fail.

**Comment by ccrama** [comment] 2016-03-30 21:29
Still cannot reproduce doing exactly the same steps. Will get access to that S5 in the next few days, hopefully can confirm your findings and fix!

**Comment by bantar** [comment] 2016-04-13 15:15
I've been keeping an eye on this for a while and I know I last tested it in 5.1.4, not 100% sure that I tested it with 5.1.5, however, now with 5.1.6 Alpha, it's fixed.   I tried all variations noted in this bug report.    I think you've fixed this.  Thanks.

**Comment by ccrama** [comment] 2016-04-13 15:18
That's awesome too hear! Happy to close this one

**Comment by bantar** [comment] 2016-04-13 16:21
We need to reopen this bug report.   It's demise was premature.   It's still there.  I'm seeing SOME imgur images work, but all GIFs and Imgur Albums are failing.

**Comment by bantar** [comment] 2016-04-13 16:46
It felt like my phone was poisoned by some action.  Things that occurred this morning were a phone reboot, followed by a Play Store load of 5.1.6.  All seemed to be working ok with images.   Then, a GIF or imgur album seemed to be a catalyst that restarted the failures.

It got so bad, that just rotating in the main view and back was resetting to position 1 (the top of the list).

So, I've just rebooted the phone, cleared the Slide cache and tried again.    This clears up some behavior.  It's no longer completely wonky, with just rotation, but I have to follow the test steps to get it to fail.   After a few more failures, we're back to a simple rotation fail pattern.

So, I rebooted the phone and did NOT clear the slide cache.   This did not change the behavior.  What ever is failing is related to the cache, I guess.   I should note that the cache is 32KB and the data is 17.73 MB.  

So, this time, I killed slide, cleared the cache and restarted slide.   Image view and rotation failed again.

So, I rebooted the phone, cleared the cache and restarted slide.   Image view and rotation failed again.

I'm at a loss.  There's no pattern of working vs failing.     Please note:  For each of these tests, I'm using the same steps.  I start in all with hot, then scroll down 25+ messages to a random message and test.   I used this same random message each time for consistency.

**Comment by seizonsenryaku** [comment] 2016-04-15 15:38
I've managed to reproduce this with this instructions:

> Start at top, scroll to imgur image, Rotate H, click on image while H, then rotate V, then back out. Notice, the position has returned to the top of the list.

I'm using a Galaxy S5, but I'm on Cyanogenmod 13 (Android 6.0.1), so this might not be a device specific firmware bug after all. Slide version: 5.1.3

**Comment by ccrama** [comment] 2016-04-19 14:51
Might not be a firmware bug, but a hardware issue be auden it's only GS5's on any software

**Comment by bantar** [comment] 2016-04-19 15:39
I take it you've not been able to get your hands on an S5?   

This only fails on Slide.  Other reddit apps never fail with rotation (that I've seen).   

What's interesting is that the main view reloads (and thus resets its position) during the picture rotation from H -> V.   You can see the main thread behind some pictures and tell exactly when it reloads.   So, I assume that you get an event notification on the rotation and reload both the image and the main view.    My guess is that the bug starts when on the main view and we rotate from V -> H.   The position is lost before the redraw on the 2nd rotation back from H -> V.       

Also, I've just verified that imgur is not the sole cause of the failure.  i.reddituploads.com fails identically.

**Comment by ccrama** [comment] 2016-04-20 19:52
No, haven't been able to, but no one on any other device has reported this. And yeah that's how rotation is handled in Android, it does the same thing for every rotation and the screen open on top will have no effect on how it works underneath. It should fail identically with every type of content open

**Comment by ccrama** [comment] 2016-04-25 22:08
Added the screenSize|screenLayout|uiMode config changes to the manifest, which will hook into three more (rare) config changes, but might be what's occurring for you, specifically:

"The user interface mode has changed — this can be caused when the user places the device into a desk/car dock or when the night mode changes. See UiModeManager. Added in API level 8."

"The screen layout has changed — this might be caused by a different display being activated."

and 

"The current available screen size has changed. This represents a change in the currently available size, relative to the current aspect ratio, so will change when the user switches between landscape and portrait. However, if your application targets API level 12 or lower, then your activity always handles this configuration change itself (this configuration change does not restart your activity, even when running on an Android 3.2 or higher device)."


If this doesn't fix the issue (the next prod update), I am really out of all ideas :(

**Comment by ccrama** [comment] 2016-04-26 01:29
So I could not reproduce on a stock gs5, it has to be something specific to your device or a device setting

**Comment by bantar** [comment] 2016-04-26 18:15
Do you have details on that Stock S5?   I too tried this on a stock S5 (never had any reddit app installed on it) and it failed identically.   Of course, these are the same model (SM-G900V) and carrier - Verizon.   I'm still trying to get other Samsung device owners to try this in the subreddit, but volunteers are fleeting...

**Comment by ccrama** [comment] 2016-04-26 19:18
I'm pretty sure it was a stock Version S5, no root or custom rom or anything

**Comment by seizonsenryaku** [comment] 2016-04-27 10:39
I tried to debug this today, but it turns out I can't reproduce with the current git version (ea7fc5a86a54754ee758b9aa15c72a98ebe683a5) so I do think this will get fixed in the next prod update.

**Comment by seizonsenryaku** [comment] 2016-04-27 12:33
I've submitted a push request that fixes the issue for me. I think the issue didn't happen when using the pro version, because it uses the method StaggeredGridLayoutManager.findFirstVisibleItemPositions, which is orientation independent.

**Closed** 2016-04-27 14:39 UTC
Labels: bug, needs reproduction
