### ISSUE TITLE
Jumpy/Changing preview picture when scrolling it onto the screen. Video capture included

### ISSUE THREAD

**Issue by brentgsw** [ccrama/Slide#837] opened 2016-01-19 20:23 UTC
This was on a build from a build this morning up to date form the last commit of Jan 18th. 
http://vid.me/W8dc

**Comment by l3d00m** [comment] 2016-01-19 20:28
Relevant part starts at 0:20. This was also reported on reddit & g+.

**Comment by ccrama** [comment] 2016-01-20 00:25
That shouldn't be possible because I changed it to use the PrecachingLayoutManager, which creates the views one before and after being displayed. The only reason this would occur still is if you have multicolumn portrait enabled or it's not up to date with master (it's the old code that was there before 4.5 where we had no issues)

**Comment by 530farm** [comment] 2016-01-20 00:56
Like I said,  this was on a build with up to date code from last night. The dual column portrait  mode was not selected.

**Comment by ccrama** [comment] 2016-01-20 00:56
I cannot reproduce this at all :(. I reverted the code to what it was pre-4.5, did you have issues before as well?

**Comment by 530farm** [comment] 2016-01-20 01:40
I noticed jumpy scrolling, but never noticed or at least caught the actual picture change behaviour

**Comment by ccrama** [comment] 2016-01-20 01:58
This is what I see https://vid.me/XCG4

**Comment by 530farm** [comment] 2016-01-23 07:07
FYI, Still seeing this on the latest build. Nexus 6p
https://vid.me/YRAb

**Comment by ccrama** [comment] 2016-02-16 01:22
Has been fixed with the new image sizing settings in 4.6

**Closed by ccrama** 2016-02-16 01:22 UTC
Labels: bug
