### ISSUE TITLE
note 2 kitkat

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#299] opened 2015-10-27 10:45 UTC
a lot of crashes 

Debug info:
 OS Version: 3.0.101-India-v4.4.6-OC-INTL-STOCK_HYBRID-KitKat(N910CXXU1ANK5)
 OS API Level: 19
 Device: trelte
 Model (and Product): SM-N910C (treltexx)
 RELEASE: 4.4.4
 BRAND: samsung
 DISPLAY: ECLIPSE V4 BY AC
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: smdk4x12
 MANUFACTURER: samsung

Stacktrace: 

```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{44985610 position=32 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent}
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at me.imid.swipebacklayout.lib.SwipeBackLayout.onLayout(SwipeBackLayout.java)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:15860)
	at android.view.ViewGroup.layout(ViewGroup.java:4916)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2382)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2095)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1270)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6658)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
	at android.view.Choreographer.doCallbacks(Choreographer.java:613)
	at android.view.Choreographer.doFrame(Choreographer.java:583)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5635)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ccrama** [comment] 2015-10-28 22:27
Dupe of #303

**Closed by ccrama** 2015-10-28 22:27 UTC
Labels: autoreport
