### ISSUE TITLE
crash on opening a reddit link from the same subreddit's sidebar

### ISSUE THREAD

**Issue by plumbe0** [ccrama/Slide#377] opened 2015-11-06 15:39 UTC
opening a link that points to a post in the same subreddit from the subreddit's sidebar causes the crash

Debug info:
 OS Version: 3.10.49-g1b64cfc(v7SSV-0)
 OS API Level: 21
 Device: idol3
 Model (and Product): 6045Y (6045Y)
 RELEASE: 5.0.2
 BRAND: TCL
 DISPLAY: LRX22G release-keys
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: qcom
 MANUFACTURER: TCL
 SLIDE VERSION: 73

Stacktrace: 

```java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at me.ccrama.redditslide.Adapters.CommentAdapter.reset(CommentAdapter.java:144)
	at me.ccrama.redditslide.Fragments.CommentPage.doData(CommentPage.java:301)
	at me.ccrama.redditslide.Adapters.SubmissionComments$LoadData.onPostExecute(SubmissionComments.java:85)
	at me.ccrama.redditslide.Adapters.SubmissionComments$LoadData.onPostExecute(SubmissionComments.java:71)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5258)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by l3d00m** [comment] 2015-11-06 15:40
Dupe of #363

**Closed by l3d00m** 2015-11-06 15:40 UTC
