### ISSUE TITLE
Lag while loading new post from multireddit

### ISSUE THREAD

**Issue by isiah-lloyd** [ccrama/Slide#2424] opened 2017-04-21 22:20 UTC
Slide version: v5.6-alpha1
Android version: 7.0

I have a multireddit with about 15 subreddits in it. Everytime I scroll through the posts and the next "page" of posts starts to load, the app slows to a stall for up to thirty seconds.

**Comment by ccrama** [comment] 2017-04-21 22:21
I am not able to reproduce this, mind uploading a video of that occurring?

**Comment by isiah-lloyd** [comment] 2017-04-21 22:40
@ccrama https://gfycat.com/CharmingFairJumpingbean 

Notice my attempts to move the screen and the spinner stopping every time a new section of posts is loaded

**Comment by ccrama** [comment] 2017-04-21 22:52
Can you try on the latest alpha? Alpha #2

**Comment by ccrama** [comment] 2017-04-22 18:44
Should be fixed now

**Closed by ccrama** 2017-04-22 18:44 UTC
Labels: needs reproduction
