### ISSUE TITLE
Can't change layout of frontpage

### ISSUE THREAD

**Issue by Tunous** [ccrama/Slide#110] opened 2015-10-16 21:17 UTC
Editing it from settings doesn't do anything and when trying to press on "i in circle" button nothing happens.

**Comment by ccrama** [comment] 2015-10-17 01:56
That is on purpose. All and frontpage take the default from settings. Ill think about re-adding it in the future, though.

**Comment by l3d00m** [comment] 2015-10-17 06:57
Duplicate of #110?

**Comment by ccrama** [comment] 2015-10-17 12:58
Closing. Duplicate of #95

**Closed by ccrama** 2015-10-17 12:58 UTC

**Comment by Tunous** [comment] 2015-10-17 13:44
I don't think it's duplicate.
> All and frontpage take the default from settings. Ill think about re-adding it in the future, though.

This is the issue. Changing default setting doesn't do anything. I have set default layout to small card but frontpage still displays using list.

**Comment by l3d00m** [comment] 2015-10-17 13:47
You probably set it before the update. Have you tried clearing app data?

**Comment by Tunous** [comment] 2015-10-17 13:52
Yes that was it. Thanks.
