### ISSUE TITLE
"open in browser" not working

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#810] opened 2016-01-15 21:43 UTC
It opens the current post in a new view. You can actually keep hitting "open in a browser" over and over again so you have to hit back multiple times to get out of the post view.

![screenshot_20160115-153745](https://cloud.githubusercontent.com/assets/3341/12366049/553a477e-bb9e-11e5-8d3f-e7980ea533c9.png)

**Comment by l3d00m** [comment] 2016-01-17 20:02
I cannot reproduce this on the newest play store version. Which version are you using?

**Comment by abraham** [comment] 2016-01-18 00:31
v4.5.0 from the play store. This is what I'm seeing https://goo.gl/photos/vxqUpS5RX45HMFMN6

**Comment by kufii** [comment] 2016-01-28 14:34
happening for me too

**Comment by ccrama** [comment] 2016-03-12 22:15
Fixed!

**Comment by Georgiel** [comment] 2016-07-18 12:49
This is still happening for me.

Version 5.3.9.3 
Android M
Xperia z5 (standard)

**Comment by Alexendoo** [comment] 2016-07-18 12:51
I shall look into it @Georgiel

**Comment by Georgiel** [comment] 2016-07-18 12:51
@Alexendoo just edited in a little more detail to help.

**Comment by Alexendoo** [comment] 2016-07-18 16:08
When #1935 is merged and hits an update near you, should be all good again.

**Closed** 2016-07-18 16:35 UTC
Labels: bug, needs reproduction
