### ISSUE TITLE
inserting special characters into the subreddit search box such as 3 or _ crashes it

### ISSUE THREAD

**Issue by sghmk12** [ccrama/Slide#136] opened 2015-10-18 04:00 UTC
## Info
type a word and then a number or special chracter. either this character doesn't type on any keyboard app or it crashes the app
## Stacktrace
```java.lang.IndexOutOfBoundsException: setSpan (0 ... 5) ends beyond length 4
at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:352)
at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:79)
at android.text.SpannableString.setSpan(SpannableString.java:46)
at android.text.TextUtils.copySpansFrom(TextUtils.java:1041)
at me.ccrama.redditslide.SubredditInputFilter.filter(SubredditInputFilter.java:29)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:491)
at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:445)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
at android.os.Handler.disp
atchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(N
ative Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)```
Reported via Slide Crash Capture

**Comment by ccrama** [comment] 2015-10-18 04:21
Dupe of #133

**Closed by ccrama** 2015-10-18 04:21 UTC
