### ISSUE TITLE
Uploading image on self text does not insert on cursor position

### ISSUE THREAD

**Issue by vcantu** [ccrama/Slide#2221] opened 2016-10-07 06:29 UTC
Slide version: v5.5 alpha2-dirty
Android version: 7.0 & ChromeOS

When you use the add image link to the self text textbox, it adds it to the front of the text instead of in the position of the cursor. I have to constantly cut and paste it in the right place.

**Comment by ccrama** [comment] 2016-10-14 21:35
I cannot reproduce this, when did this issue begin occurring?

**Comment by vcantu** [comment] 2016-10-14 21:53
I noticed this when I was writing a post on ChromeOS. I went to the phone version to check if it was ChromeOS or the app but it happens on both.

Here is a video:
`https://drive.google.com/file/d/0B_jWNL0vEC72dGpUY1FObVJYQ3c/view?usp=sharing`

**Comment by ccrama** [comment] 2016-10-14 21:57
Thanks for the find, should be fixed now!

**Closed by ccrama** 2016-10-14 21:57 UTC
Labels: cosmetic
