### ISSUE TITLE
some thumbnails and blank thumbnails not clickable

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#332] opened 2015-11-01 21:17 UTC
eg in /r/androidapps/

"Would you buy this game? (Collecting data for a school project.)"
"Does anyone use TickTick? Waht are the pros and cons?"

**Comment by ccrama** [comment] 2015-11-01 21:21
Cannot reproduce. Can you give me a direct link please?

**Comment by c727** [comment] 2015-11-01 21:39
I made a video. download here: http://www.xup.in/dl,13858965/2015_11_01_22_27_25_trim_00-00_00-42.mp4/

**Comment by ccrama** [comment] 2015-11-02 14:37
Can't play :(

**Comment by c727** [comment] 2015-11-02 16:18
Hmmm. I tested the video on my phone and PC before the upload. I will check the upload when I'm at home.

OK...
Lets take this http://reddit.com/r/androidapps/comments/3r7tqb/dev_pawwzle_slide_puzzle_alarm_app_with_images/

In now for reddit it has no thumbnail (in /r/androidapps), in slide it has a thumbnail which ist not clickable.

Also in now (and slide in the versions before latest) on posts without thumbnail you can click where the thumbnail would be placed and it opens/opened the thread. Thats also broken now.

**Comment by c727** [comment] 2015-11-02 16:36
Thumbnail width should have a fixed value
http://abload.de/img/screenshot_2015-11-02jougr.png

**Comment by c727** [comment] 2015-11-03 16:50
https://youtu.be/b96HVtrnJwI

**Comment by ccrama** [comment] 2015-11-05 05:36
Selftext posts can have images in Slide, these aren't clickable because they are pulled from context and not a direct link. That isn't a bug, it's a feature

Same with the thumbnail width, as it distorts the images if I have a fixed width.

Thank you for the reports though!

**Comment by c727** [comment] 2015-11-05 06:54
Makes no differnece for the user if it's pulled from the content or not. The user doesn't want to check this first before he can decide if a picture is clickable or not.

Also afaik these pics (and the empty boxes) were clickable in the past...
Reopen please ;p

**Comment by ccrama** [comment] 2015-11-05 15:45
Ok you were right. Fixed with 853f16db6572c02c3f1fa479ac9240e8ddc92c4d

**Closed by ccrama** 2015-11-05 15:45 UTC
Labels: bug

**Comment by mattlyons0** [comment] 2016-01-19 12:16
I think this is the same issue again. Links to websites that do not have a thumbnail (like this https://www.reddit.com/r/teslamotors/comments/41lhq7/meet_the_maker_of_the_tesla_model_xs_big_sky/ ) are not openable. They appear as selfposts with no content.

**Comment by l3d00m** [comment] 2016-01-19 13:22
@mattlyons0, you're correct, #805 was the issue for that. It is fixed with next release.
