### ISSUE TITLE
Unable to load frontpage on alternative account?

### ISSUE THREAD

**Issue by kyoraki** [ccrama/Slide#2526] opened 2017-09-15 02:18 UTC
Slide version:5.6.2
Android version: 8.0.0
Got a weird bug here where I can't load the frontpage of any accounts besides the primary one, I log into a different B account and it just loads the frontpage of the other, still keeping my logged into the previous A account and everything.

**Comment by ccrama** [comment] 2017-09-15 03:12
Thanks for the report! Duplicate of #2518 on Android Oreo

**Closed by ccrama** 2017-09-15 03:12 UTC
