### ISSUE TITLE
Toggle to confirm before exiting/sliding back out to post listing

### ISSUE THREAD

**Issue by SaladMandrake** [ccrama/Slide#1554] opened 2016-04-25 13:51 UTC
A new toggle to confirm before going back out to post listing. Slide is really nice and convenient with all the sliding, but I kept accidentally slide back out to post listing when I meant to slide to previous post.

**Comment by Nxt3** [comment] 2016-04-25 18:46
You are just sliding from too far over. If you're trying to go back to a previous post by sliding--start more from the middle. 

I really don't think a dialog is the way to go--as this is such a niche feature.

**Comment by ArthurHeng** [comment] 2016-04-25 19:04
Point taken, but further tuning the slide to exit sensitivity might vastly improve user experience, just my opinion =).

**Comment by Nxt3** [comment] 2016-04-25 19:15
I'm pretty sure it was adjusted when @ccrama changed how the swipeback was accomplished. Not sure there is much else to change--I don't have any problem with this and ever since the change--I don't think anyone else has either.

**Comment by ArthurHeng** [comment] 2016-04-25 19:33
https://reddit.com/r/slideforreddit/comments/4gcw4n/disable_sliding_out_of_albums/

Here is at least one more person having issues with sliding aspect of the app.

**Comment by Nxt3** [comment] 2016-04-25 19:35
Yeah--in the albums. The albums don't happen to use the new slide system for whatever reason. See #1283

**Comment by Alexendoo** [comment] 2016-04-25 19:36
I think this isn't that @Nxt3 but the swiping in from the edge (trying to go back an image) though yeah that's an issue as well. I do agree a bit that it's rather strange to have two distinct actions on roughly the same gesture, can be a bit unintuitive, not sure what would be best there though

**Comment by Nxt3** [comment] 2016-04-25 19:38
@Alexendoo I'm not sure I understand. The album view doesn't use the new way of swiping back. As a result, it is far more sensitive.

If you swipe back from the middle of the screen--you'll go back an image; if you swipe from the far left side of the display--you'll leave the album. It isn't unintuitive.

**Comment by ccrama** [comment] 2016-04-25 19:42
I agree with @Nxt3 , I use both actions and they are both very different actions

**Comment by Alexendoo** [comment] 2016-04-25 19:48
For the first part @Nxt3 I was saying yes, that's an issue, but not the one the post/this thread is talking about.

For a large device I can appreciate that yeah, I haven't had it happen since using a nexus 5 because it takes a lot of movement to get over to the left edge, but with a smaller device it happened quite a lot

**Comment by ArthurHeng** [comment] 2016-04-25 19:55
Sorry about the mis close, my keyboard bugged out on me, have to reboot the phone.

Anyway, it's rather subjective whether it's different or not. IMO it's slightly different but very similar and users could easily make mistakes and quit when it's unintended, I myself and that guy in the Reddit link above. You could deny it but my mistakes are really happening.

I could still use the app without any of those improvements, but it's all about the user experiences that won people over.

**Comment by Nxt3** [comment] 2016-04-25 20:18
@Alexendoo I know, but he posted a link to someone having issues with the album view swipe. I was responding to that. 

You guys are talking about two different issues. The album swipe back has it's own problem independent of the problem this issue addresses. 

@ArthurHeng Maybe it is sensitive, maybe it isn't. You're the only person who has issue with the swipe back mechanism in comment view though. Adding an option is too niche and there really isn't much else that can be done in terms of sensitivity. We're using a page in a ViewPager to fake a "blank" page to swipe back to. This is something Android natively has. As a result, it isn't easy (and in some cases, even possible), to modify something like the swiping sensitivity.

**Comment by Alexendoo** [comment] 2016-04-25 20:28
@Nxt3 The difference between the old & new systems are for vertical scrolling (see #957), it's the angle at which swipe from anywhere is triggered that changed, not the distance to the edge to trigger the (non swipe from anywhere) exit gesture

The issue here purely the fact that swiping in from the right can have two different actions, and it's easy to (on smaller devices at the least) catch the boundary for what's considered the edge of the screen and thus lose your place

**Comment by ArthurHeng** [comment] 2016-04-25 20:30
Chances are for everything I reported/requested, there are only 1-3 person reporting and requesting, doesn't mean it's niche. If you haven't figured out a way to minimize the user mistake of those two actions that are so similar to each other, the toggle is a really simple solution to it.

Once the app gains popularity, even a niche feature will become immensely helpful, especially to new comers.

**Comment by ccrama** [comment] 2016-04-25 20:32
Well out of 70k users, only a handful have reported it

**Comment by ArthurHeng** [comment] 2016-04-25 20:34
Those two actions are used throughout the entire app, combined with non-technical users, you will have a lot of users keep backing out when they meant to slide to previous. Now how is that niche.

**Comment by ccrama** [comment] 2016-04-25 20:35
It's niche to disable it because the vast majority of my users use that as a top level action to close views, as it's enabled on every view in the app

**Comment by ArthurHeng** [comment] 2016-04-25 20:40
A handful means I'm not the only person with that problem. I consider myself to be quite a dedicated user as this and opengur are the only two reader apps I use extensively, daily. This phone might as well be part of my organ and even I make mistakes of sliding the wrong way.

Unless you guys are planning to change the interface and gestures so much until this toggle no longer serves any function, I think this is a good function to have.

**Comment by ArthurHeng** [comment] 2016-04-25 20:42
Well, my objective is, either add a toggle to confirm before backing out, or increase the gap between two types of swipe/slide.

**Comment by ccrama** [comment] 2016-04-25 20:51
Alright, I'll look into it. The issue is disabling it will disable it on every view

**Comment by ArthurHeng** [comment] 2016-04-25 20:54
My suggestion is to add a toggle to show a **confirmation **dialogue when user swipes to exit. Just like the Confirm Exit Dialog, but for backing out to post listing.

**Comment by ArthurHeng** [comment] 2016-04-25 20:56
Anyway, hope I didnt cause any offense.

**Comment by Nxt3** [comment] 2016-04-25 21:48
@ArthurHeng The problem with a toggle, with what ccrama is saying--is that if you do put a toggle in, you'd have to put that confirmation _everywhere_ there is a swipeback gesture--otherwise, it would be largely inconsistent; the issue is that this is an app called "Slide"; you'd expect the primary way of navigation to be "sliding" around. Hindering that motion would be aggravating--maybe if it was only enabled with one view it would be fine; but from a UX point of view--it would be expected that this dialog shows everywhere. At that point, the app loses its "uniqueness".

**Comment by ccrama** [comment] 2016-04-25 21:50
@Nxt3  he does have a point about it though, but I think a compromise might be to have a button to disable swiping back from comments and vertical albums. This seems to be where most of the issues occur with this, and @ArthurHeng  could still swipe back to exit from the first post in the list.


What are you guys' thoughts on this?

**Comment by ccrama** [comment] 2016-04-25 21:51
Whoops

**Comment by Nxt3** [comment] 2016-04-25 21:52
@ccrama Is there a reason you can't use the ViewPager page for vertical albums? I figured that would help with that.

So you propose a setting that disables swiping back from everywhere? It's weird to disable swiping back from just two places--otherwise.

**Comment by ccrama** [comment] 2016-04-25 21:53
No, just disabling from comments and albums. And it's not that I can't, but I'd have to turn the activity into a fragment and put that into a ViewPager, which is a lot of work

**Comment by Nxt3** [comment] 2016-04-25 21:55
I guess that makes sense. Still seems niche to me; if I didn't want to slide around--I'd use Sync or some other client.

**Comment by Alexendoo** [comment] 2016-04-25 21:58
The vertical album one I do find myself doing occasionally but I think that's a slightly different issue, not sure I'd want to disable it entirely as I do like swipe anywhere to exit.

The issue would still be there with a fair few things with that, e.g. horizontal albums, shadowbox come to mind.

I don't think I'd want a setting added for disabling swiping to exit from 2nd + pages in those views (the original suggestion) rather pick a default and stick to it. That said I would enable it if it were an option. I can't think of a decent alternative. Maybe enable comment pane to load more comment threads? would alleviate it there at the very least as there's no swipe from the edge to exit

**Comment by ccrama** [comment] 2016-08-06 20:04
This has been tweaked a lot since a few months ago, closing this for now.

**Closed by ccrama** 2016-08-06 20:04 UTC
Labels: feature request
