### ISSUE TITLE
minor design bug: different fonts

### ISSUE THREAD

**Issue by ente3000** [ccrama/Slide#1920] opened 2016-07-15 08:27 UTC
Slide version: 5.3.9.5
Android version: 6.0.1

http://imgur.com/SWdPMKK

**Comment by Alexendoo** [comment] 2016-07-15 09:55
Fonts? The numbers look like roboto to me which is the standard, what exactly is wrong in the image

**Comment by ente3000** [comment] 2016-07-15 10:01
@Alexendoo If you look closely you can see that the upvote count uses the system font (I'm currently using a CM theme whose font is Roboto Condensed) and the comment count uses the font specified by the user (Roboto Light in my case).

**Comment by Alexendoo** [comment] 2016-07-15 10:27
Ah yes I see it, where is this happening? I don't believe the action bar takes on the font the user chooses, but it does make the score bold when up/downvoted

**Comment by ente3000** [comment] 2016-07-15 11:16
@Alexendoo everywhere ._. and I didn't vote on the post in the screenshot, otherwise the score would be colored

**Comment by Alexendoo** [comment] 2016-07-15 12:23
I suspect it's down to the (many) occurrences of `{score TextView}.setTypeface(null, Typeface.NORMAL)` throughout the codebase

**Comment by ccrama** [comment] 2016-07-15 14:29
That is actually on purpose, the score is bold system while the comments are regular user

**Comment by Alexendoo** [comment] 2016-07-15 14:42
The score is only bold when up/downvoted: e.g. https://github.com/Alexendoo/Slide/blob/31093ff4d32080419ca0b9cd0539887ce3645d0f/app/src/main/java/me/ccrama/redditslide/SubmissionViews/PopulateSubmissionViewHolder.java#L1579-L1608 and repeated in a few other places

I'm not sure where the comment score gets its typeface from

**Comment by ccrama** [comment] 2016-07-15 14:43
Neither are set on purpose, except bold on the score. Both use the system font, just one is bolded and one isn't

**Comment by Alexendoo** [comment] 2016-07-15 14:44
In the linked image no vote is cast, thus they should both be regular but are not

**Comment by ccrama** [comment] 2016-07-15 14:47
Don't quite know about that, but the issue isn't dealing with the user set font, the issue is that the recycled view is keeping the bolding from a previous upvote

**Comment by Alexendoo** [comment] 2016-07-15 14:54
Here is the behaviour with an unchanged system font

![image](https://cloud.githubusercontent.com/assets/1830331/16878203/8f2c31ba-4aa3-11e6-9fa3-39a238e4d4ec.png)
![image](https://cloud.githubusercontent.com/assets/1830331/16878294/e7a0e3b8-4aa3-11e6-8d95-1a652c2ac85e.png)

Can it be the recycled view doing that? The typeface for the score is set explicitly on all vote cases (up, down, none) when it's populated

**Comment by ccrama** [comment] 2016-07-15 14:57
Yes, for some reason @ente3000 's recycled view didn't get reset. FWIW, I cannot reproduce this issue

**Comment by Alexendoo** [comment] 2016-07-15 15:09
What theme are you using @ente3000?

**Comment by ente3000** [comment] 2016-07-15 16:11
@Alexendoo Caffene https://play.google.com/store/apps/details?id=com.b16h22.caffene

**Comment by Alexendoo** [comment] 2016-07-15 16:18
Does a similar thing happen with another theme (preferably free), or without a theme?

**Comment by ente3000** [comment] 2016-07-15 16:40
@Alexendoo I don't have many free themes, and those who are free don't have a custom font.
However, I tried with multiple other themes. Most of them don't have this issue, but one of them does: [Radius](https://play.google.com/store/apps/details?id=com.kohlewrrk.radius).
![utegfbt](https://cloud.githubusercontent.com/assets/8181990/16881540/fbfdbe82-4aba-11e6-9ad9-7bd315f31ae6.jpg)
Also Caffene Light (obviously).

**Comment by ccrama** [comment] 2016-07-15 16:42
This seems to be an issue with the themes rather than an issue with Slide, no? Considering this can't be reproduced on stock android

**Comment by Alexendoo** [comment] 2016-07-15 16:57
I suspect an OS that used a different font could have similar issues

**Comment by ccrama** [comment] 2016-08-30 22:20
I think this is now fixed, there were some changes to the fonts and I have not been able to reproduce this

**Closed by ccrama** 2016-08-30 22:20 UTC
Labels: cosmetic
