### ISSUE TITLE
Open post while loading

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#922] opened 2016-01-29 22:26 UTC
Clicking on the last post in the list while more are loading (there is a loading icon right below) crashes Slide.

**Comment by l3d00m** [comment] 2016-01-31 11:00
I can't reproduce it on 791749c505292206b7c86a8ef62bc67226e4990c.
We had this problem a while back (#153), but that was fixed with https://github.com/ccrama/Slide/pull/818. Do you have a stacktrace by any chance?

**Comment by anandroiduser** [comment] 2016-01-31 14:26
```01-31 09:23:24.237 E/AndroidRuntime(26315): FATAL EXCEPTION: main
01-31 09:23:24.237 E/AndroidRuntime(26315): Process: me.ccrama.redditslide, PID: 26315
01-31 09:23:24.237 E/AndroidRuntime(26315): java.lang.IndexOutOfBoundsException: Invalid index 25, size is 25
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at java.util.ArrayList.get(ArrayList.java:308)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at me.ccrama.redditslide.Activities.CommentsScreen$OverviewPagerAdapter.getItem(CommentsScreen.java:160)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.support.v4.app.FragmentStatePagerAdapter.instantiateItem(FragmentStatePagerAdapter.java:105)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:870)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.View.measure(View.java:18794)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.View.measure(View.java:18794)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.View.measure(View.java:18794)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.View.measure(View.java:18794)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.View.measure(View.java:18794)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.View.measure(View.java:18794)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
01-31 09:23:24.237 E/AndroidRuntime(26315): 	at android.view.View.measure(View.java:18794)
```

**Comment by ccrama** [comment] 2016-02-01 21:15
That was fixed many commits back

**Closed by ccrama** 2016-02-01 21:15 UTC
Labels: crash
