### ISSUE TITLE
App still crashing on some posts

### ISSUE THREAD

**Issue by sharedkestrel** [ccrama/Slide#2701] opened 2018-03-31 07:58 UTC
I'm on the new alpha2, and I can open most of the comments that I previously couldn't, but some posts, like [this](https://www.reddit.com/r/leagueoflegends/comments/88fco2/tryndamere_has_a_medical_condition_called_situs/), still have comments that make the app crash.

**Comment by PiwwowPants** [comment] 2018-03-31 10:09
I cannot reproduce a crash on that post. Any others potentially causing an issue?
What device and OS version are you running (mostly OS version).

**Comment by sharedkestrel** [comment] 2018-03-31 10:30
@PiwwowPants I'm on LineageOS, Android 7.1

The crash only happens on some posts, not all of them, and only when scrolling down to certain comments, apparently. Is a normal logcat okay or are there special steps to get a log of the crash?

**Comment by PiwwowPants** [comment] 2018-03-31 10:36
Logcat is fine either here (if not humongous) or via a pastebin in link. That'll probably help narrow this down

**Comment by sharedkestrel** [comment] 2018-03-31 10:40
https://pastebin.com/V6gXN03x

This should be fine, I think

**Comment by PiwwowPants** [comment] 2018-03-31 15:33
I believe this post may be causing a crash for you still? (It's still for me but I'm not near a computer)

https://www.reddit.com/r/slideforreddit/comments/874lbb/translations_are_not_getting_pushed/

**Comment by sharedkestrel** [comment] 2018-03-31 16:04
I can view that post no problem 🤔

**Comment by ccrama** [comment] 2018-03-31 23:56
@sharedkestrel can you go to Settings > About Slide > long press on version number and paste that crash report here? That keeps the last active crash log

**Comment by sharedkestrel** [comment] 2018-04-01 09:35
@ccrama Yesterday I uninstalled, installed again, and now the problem is solved. Maybe something was still in the cache?

**Comment by PiwwowPants** [comment] 2018-04-01 12:45
I believe I just didn't see all the calls to getAuthorFlair the first time so I missed some null check fixing.

I'm hopefully this PR fixes these issues https://github.com/ccrama/Slide/pull/2702

**Comment by ccrama** [comment] 2018-04-01 15:26
Should be fixed now!

**Closed by ccrama** 2018-04-01 15:26 UTC
