### ISSUE TITLE
Per-account theme is not properly applied when switching accounts

### ISSUE THREAD

**Issue by tp0** [ccrama/Slide#2858] opened 2018-09-23 10:12 UTC
The default base theme that is set at the first launch of Slide is partially applied when switching another account with a different theme.

In these screenshots:
* I have set Light theme as the default base theme at the first launch
* I have switched from Account A (theme doesn't matter) to Account B (Dark theme)
* Result: the Light theme is still applied in many areas of the UI:
   (1) Light theme in the background
   (2) Sidebar is still Light theme
   etc.
* After relauching the theme is properly and fully applied.

It doesn't matter what theme Account A has: even if it has the same theme as B, the initially selected base theme theme still shows up like in the screenshots. This is reproable with all theme(s).

Slide version: 5.9-alpha2
Android version: Nougat 7.1.2

(1)
![001](https://user-images.githubusercontent.com/5863551/45926866-2253fe00-bf32-11e8-8aed-529fb4dbfff7.png)

(2)
![003](https://user-images.githubusercontent.com/5863551/45926868-2253fe00-bf32-11e8-924b-e2716dbb1b5b.png)

**Comment by Alexendoo** [comment] 2018-11-04 16:46
Duplicate of #2857

**Closed by Alexendoo** 2018-11-04 16:46 UTC
