### ISSUE TITLE
App crashes when trying to launch from www.reddit.com link

### ISSUE THREAD

**Issue by amandaoneal** [ccrama/Slide#2611] opened 2018-01-02 15:20 UTC
Works correctly: 
1. Have Slide opened in the background from previous usage
2. From another app open a link to a Reddit page (format: http://www.reddit.com/r/news/comments/7nj9j4/recordbreaking_big_freeze_grips_much_of_north/) 3. Say 'open with Slide'
4. It opens correctly.

Does not work:
1. Force-close Slide so that it's not open in the background
2. From another app open a link to a Reddit page (same format as above) 
3. Say 'open with Slide'
4. It crashes.

Slide version: 5.7.2
Android version: 5.1.1

**Comment by ccrama** [comment] 2018-01-03 15:16
Not able to reproduce on my devices

**Comment by Tensounder54** [comment] 2018-11-09 15:37
This issue is resolved in a later verstion of slide and needs to be closed.

**Closed** 2018-11-09 16:00 UTC
Labels: needs reproduction
