### ISSUE TITLE
Randomly crashes when im in other apps

### ISSUE THREAD

**Issue by RohitMadhu** [ccrama/Slide#293] opened 2015-10-27 02:35 UTC
randomly crashes while in other apps

Debug info:
 OS Version: 3.4.0-Sultan-CAF(b54fdc550a)
 OS API Level: 22
 Device: A0001
 Model (and Product): A0001 (bacon)
 RELEASE: 5.1.1
 BRAND: oneplus
 DISPLAY: LVY48F release-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: bacon
 MANUFACTURER: OnePlus

Stacktrace: 

```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Could not execute the request: HttpRequest {method='GET', url=https://oauth.reddit.com/api/multi/mine?expand_srs=true, expectedMediaType=application/json, headers=User-Agent: android:me.ccrama.RedditSlide:v4.0 (by /u/ccrama)
Authorization: bearer 15362258-4v1AG4IrIA9_hNqr8vHYNOWGS1U
, body=null}
	at net.dean.jraw.http.RestClient.execute(RestClient.java:144)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
	at net.dean.jraw.managers.MultiRedditManager.mine(MultiRedditManager.java:42)
	at me.ccrama.redditslide.SubredditStorage.getMultireddits(SubredditStorage.java:259)
	at me.ccrama.redditslide.SubredditStorage.doInBackground(SubredditStorage.java:51)
	at me.ccrama.redditslide.SubredditStorage.doInBackground(SubredditStorage.java:27)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Caused by: java.net.UnknownHostException: Unable to resolve host "oauth.reddit.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
	at java.net.InetAddress.getAllByName(InetAddress.java:215)
	at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
	at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
	at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
	at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at com.squareup.okhttp.Call.getResponse(Call.java:271)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
	at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
	... 12 more
```

**Comment by l3d00m** [comment] 2015-10-28 13:31
dupe of #252?

**Closed** 2015-10-28 13:32 UTC
Labels: autoreport, duplicate
