### ISSUE TITLE
Tapping on users profile

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#248] opened 2015-10-25 01:28 UTC
was reading a post, decided to check out the users profile and it crashed when clicking the username 

Debug info:
 OS Version: 3.4.0-perf-g5c87ba0-02008-gbe52486(2925005669)
 OS API Level: 22
 Device: D6503
 Model (and Product): D6503 (D6503)
 RELEASE: 5.1.1
 BRAND: Sony
 DISPLAY: 23.4.A.1.232
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: Sony

Stacktrace: 

```java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.Profile}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
	at android.app.ActivityThread.access$800(ActivityThread.java:156)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5373)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at me.ccrama.redditslide.Activities.Profile.onCreate(Profile.java:57)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
	... 11 more
```

**Comment by l3d00m** [comment] 2015-10-25 07:08
Dupe of #250

**Closed** 2015-10-25 12:56 UTC
