### ISSUE TITLE
History OFF also saves history

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#2123] opened 2016-09-05 08:58 UTC
Slide version: 5.4.2.3
Android version: 5.1.1

I'm not sure if this is intended. If I click a post the text color changes from white to grey while opening animation. When I go back to sub view the text color is white again. After refreshing the sub the text is grey again

**Comment by ccrama** [comment] 2016-09-05 15:59
If you have history turned off for that, yes it is intended

**Comment by c727** [comment] 2016-09-05 17:10
I recorded a video:
-my history is off, so this seems to be already broken cause some threads are marked as read/ are grey?!
-when I open a new post I have to refresh my sub to mark it read

https://www.youtube.com/watch?v=xCdg_J2eW7Y&feature=youtu.be

**Comment by c727** [comment] 2016-09-05 17:18
OK, History ON is the way I want it and it's working then...

But history OFF is not working as seen in my video

**Comment by ccrama** [comment] 2016-09-05 20:41
That is intended. It turns gray as you touch it but reverts when you return

**Comment by c727** [comment] 2016-09-05 21:30
Yes I got it.
But watch the Video: After a restart/refresh the post is gray again (when history is Off)

**Comment by ccrama** [comment] 2016-09-05 21:55
Do you have comment count since last visit on? That will override your
history settings

**Comment by The0x539** [comment] 2016-09-05 22:37
I've experienced this issue and don't use comments since last visit.

**Comment by ccrama** [comment] 2016-09-05 22:39
Don't really know how to reproduce that, it's working fine for me and I
haven't gotten other reports of it. Are they showing up in history on your
profile? Might be Reddit itself marking the post as read (which isn't an
issue with Slide)

**Comment by c727** [comment] 2016-09-05 23:01
comment count is off. They are not in my history at reddit.com.

Did another test:
I cleared slide's app-data and tested as guest:
-turned history Off
-opened a post
-restarted slide
-> Post is marked as read

**Comment by ccrama** [comment] 2016-09-06 21:04
Should be fixed now, I stored all the times of seen posts regardless of history settings

**Closed by ccrama** 2016-09-06 21:04 UTC
Labels: bug, needs reproduction
