### ISSUE TITLE
Blank sidebar and subreddits

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#331] opened 2015-11-01 20:48 UTC
info: my device has only 1GB ram

How to force this bug:
-open slide
-press homebutton
-open ~5 'big' apps
-go back to slide

**Comment by c727** [comment] 2015-11-01 20:53
http://abload.de/img/screenshot_2015-11-016vssg.png

**Comment by alexsmithfanning** [comment] 2015-11-01 22:02
Possibly related to #239?

**Comment by ccrama** [comment] 2015-11-02 03:35
Possibly, but it should be merged with #306 as it fits in with the general "connection" bugs

**Comment by l3d00m** [comment] 2015-11-02 15:24
Dupe of #65, it happens too with my better specs g2.

**Comment by ccrama** [comment] 2015-11-02 15:25
Happens on my 4gb RAM note 5 as well :c

**Comment by ccrama** [comment] 2015-11-05 05:37
Merging with #67

**Closed by ccrama** 2015-11-05 05:37 UTC
Labels: bug, duplicate
