### ISSUE TITLE
Sorting multis is not possible

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#300] opened 2015-10-27 10:47 UTC
1. Select multi   
2. Select sorting method other than hot  
3. Sorting method is still hot

**Comment by Alexendoo** [comment] 2015-10-27 10:51
I have the same occurring, except it's for hot rather than top

**Comment by l3d00m** [comment] 2015-10-27 10:52
That's what I meant too

**Comment by l3d00m** [comment] 2015-10-27 18:31
Problem is still persisting with newest code

**Comment by ccrama** [comment] 2015-10-28 22:26
Dupe of #303

**Comment by ccrama** [comment] 2015-10-28 22:27
Whoops. Fixing now

**Comment by ccrama** [comment] 2015-10-29 15:45
It's a bug with the API I'm using. Will be forking it and trying to fix it. Until then, marking as planned

**Comment by ccrama** [comment] 2016-01-12 22:19
Raising the zombie! @thatJavaNerd , do you know if this is an issue with JRAW or my implementation of it?

**Comment by thatJavaNerd** [comment] 2016-01-18 05:34
Where is the relevant code?

**Comment by l3d00m** [comment] 2016-01-18 05:44
Sorry that I can't link directly, but the class name is 'CreateMulti.java' and the relevant code is near the bottom of that class.

**Comment by ccrama** [comment] 2016-01-18 08:26
@thatJavaNerd Should all be here
https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Adapters/MultiredditPosts.java#L87

**Comment by ccrama** [comment] 2016-03-24 04:43
Fixed! Was a small issue with JRAW @thatJavaNerd . I detailed the issue with a fix here https://github.com/thatJavaNerd/JRAW/issues/124

**Comment by ccrama** [comment] 2016-03-24 06:17
Well that fixed sorting profiles, but not multis. Re-opening for now

**Closed** 2016-03-24 20:09 UTC
Labels: bug
