### ISSUE TITLE
Crashes on Textmode posts with image preview

### ISSUE THREAD

**Issue by bantar** [ccrama/Slide#1324] opened 2016-04-07 15:28 UTC
Slide version:  5.0.4 A2 and A3
Android version:  5.0 Galaxy S5

I can't tell if this is a new problem or not, but after fixing #1274, I'm now seeing a new image crash problem.   I can't reproduce this on demand, but I've seen it enough to call it a legitimate bug.  This is the only image crash issue that I'm seeing now.

Steps to recreate:   Find Text Mode post with an embedded image link.   Click on the picture from the main view, it opens the post.   Decide to view the picture, so click on the picture.   It beeps.  Then click on the embedded imgur URL.   Crash.

I've seen this same problem about 5-8 times, however, I'm unable to reliably reproduce the issue on any one post.   The best I've seen is crashing 2 times in a row, but 2 times is rare.  Never 3.   I've seen this 5-8 times already.    Also, I don't know if the click on the picture before the URL is important, it's just what I typically do.    It does need to be an imgur link as other basic URLs always seem to work.   I'd guess the failure rate to be about 40-50% of said text post messages (it's a guess).

**Comment by ccrama** [comment] 2016-04-07 15:37
Clicking the picture does nothing in code, can't reproduce and don't know why you're seeing this. I'll see if anyone else reports it

**Comment by bantar** [comment] 2016-04-07 15:41
OK, good to know.  Since I can't reproduce it reliably, I can't narrow the steps down to the minimum.   Based on what you said, it's a superfluous step and can be ignored.   So, its down to just clicking on the imgur URL in text posts that is the failure.

**Comment by ccrama** [comment] 2016-04-07 17:29
Do you have an example of the image url? Might be the same issue you were running into earlier

**Comment by bantar** [comment] 2016-04-07 18:01
I had only saved one as a just in case.   Here it is:  https://www.reddit.com/r/MechanicAdvice/comments/4d6kej/nail_in_the_tire_need_advice/    Image size is 945KB - 2,160px × 3,840px

I've been sharply looking for another failure, but I'm not running across many that fit this profile and so far, none have failed since opening this ticket.

**Comment by ccrama** [comment] 2016-04-07 18:31
Alright. Did you report the crash from the crash dialog?

**Comment by bantar** [comment] 2016-04-07 18:33
Yes.  I always do report crashes, unless I fat finger it away by mistake.

**Comment by ccrama** [comment] 2016-04-13 01:45
Let me know if this continues with 5.1.5!

**Comment by ccrama** [comment] 2016-04-14 23:49
Because this is related to general out of memory issues, I will be closing this and merging with the other threads about memory use

**Closed by ccrama** 2016-04-14 23:49 UTC
Labels: crash, needs reproduction
