### ISSUE TITLE
Opening reddit post crashes the app 

### ISSUE THREAD

**Issue by Gr3q** [ccrama/Slide#3045] opened 2019-08-03 11:44 UTC
Slide version: 6.2
Android version: 9.0

If I open this post, the app crashes. 

https://redd.it/clfs9f

**Comment by Gr3q** [comment] 2019-08-04 08:25
I suspect displaying one of the comments crashes the app

**Comment by expobar** [comment] 2019-08-04 20:49
Duplicate of issue [3028](https://github.com/ccrama/Slide/issues/3028)

**Closed** 2019-08-23 12:57 UTC
