### ISSUE TITLE
Comments since last visit count not updating properly

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1501] opened 2016-04-21 01:19 UTC
Slide version: 5.2.6
Android version: 6.0.1

http://i.imgur.com/2r4wpfo.jpg

Click on any post with x comments and swipe back. You'll notice that it displays (x comments) as the comments since last visit count, which is incorrect.

**Comment by ccrama** [comment] 2016-04-21 01:19
That was a bug caused by the last update which is fixed in this one, you need to open up all the links you opened last one to fix it

**Closed by ccrama** 2016-04-21 01:19 UTC
