### ISSUE TITLE
When inputting a number in the search subreddit bar the whole app crahses

### ISSUE THREAD

**Issue by sghmk12** [ccrama/Slide#188] opened 2015-10-20 10:57 UTC
## Info
App version 4.2 alpha recently updtaed
OS android 6.0 Marshmallow nexus 5 

Problem using the search subreddit bar when inputting a special character such as a number or underscore either it doesn't type or the app crashes using multiple keyboards. 
## Stacktrace
```
java.lang.IndexOutOfBoundsException: setSpan (0 ... 1) ends beyond length 0
at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:352)
at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:79)
at android.text.SpannableString.setSpan(SpannableString.java:46)
at android.text.TextUtils.copySpansFrom(TextUtils.java:1041)
at me.ccrama.redditslide.SubredditInputFilter.filter(SubredditInputFilter.java:29)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:491)
at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:445)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
at android.os.Handler.disp
atchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(N
ative Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
Reported via Slide Crash Capture

**Comment by Alexendoo** [comment] 2015-10-20 10:59
Duplicate of #143

**Closed by Alexendoo** 2015-10-20 10:59 UTC
Labels: duplicate
