### ISSUE TITLE
More customization? 

### ISSUE THREAD

**Issue by ObadaS** [ccrama/Slide#1960] opened 2016-07-22 10:10 UTC
Slide version: 5.4
Android version: 5.1.1

Hello, would it be possible to change the color of some of the things in posts? Like, if you are using the smaller tag, add a possibility to change its color from white to something else and to change its position instead of forcing it to be on the bottom right of the image. 

Also would it be possible to choose a different default color for subreddit names, instead of making it white, make it be the main theme accent color or a custom color you can choose. Something different than choosing a custom theme for each subreddit separately so that its easier to find from what subreddit the post is from. 

Thanks for this amazing app!

**Comment by Nxt3** [comment] 2016-07-22 11:50
When you say:

> Also would it be possible to choose a different default color for subreddit names, instead of making it white

Where are you referring to?

**Comment by ObadaS** [comment] 2016-07-22 12:22
> When you say:

   >> Also would it be possible to choose a different default color for subreddit names, instead of making it white

> Where are you referring to?

I am talking about the subreddit name on posts, as seen on the screenshot I took ( /r/worldnews and /r/overwatch in this case, taken from /r/all), making all the default color something other than white so that it can be easily seen if someone is scrolling more or less fast. The goal of this would be bring a little bit more coloration when browsing reddit, since all you see for now is just white text and images depending on the post.

![slide_suggestion_custom](https://cloud.githubusercontent.com/assets/11889208/17056751/35fa671c-501e-11e6-84ed-399631448339.png) 

Something like that (Taken from boost for reddit)

![screen-3-boost-reddit](https://cloud.githubusercontent.com/assets/11889208/17056985/f66d3762-501f-11e6-9d20-98fd22acfa6a.png)

**Comment by Nxt3** [comment] 2016-07-22 12:27
I don't think we should color that; I get where you're coming from, but if you want a certain sub to stand out, you'd give it a custom theme and then go to `Settings > Main Theme > Submission color tinting mode = Subreddit name`.

How about instead of coloring it--we made it **bold** instead?

**Comment by ObadaS** [comment] 2016-07-22 12:33
The problem with the setting you gave here is that you have to manually add a theme color to each subreddit. Giving us the option to change the default color to something other than white will be better when browsing /r/frontpage and /r/all ( though I get why it could also backfire, if you have lots of themed subreddits, but since we would be able to change the color we can always make it go back to white)

Making it be bold can be interesting since it will make it stand out a bit more, though I really like the idea of putting more colors instead of having only ( mostly ) one color when browsing.

**Comment by Nxt3** [comment] 2016-07-22 12:38
I'll leave it up to @ccrama to decide.

I personally think there are more than enough color/theme options for Slide--adding this setting just makes the already crowded settings area more crowded. We're currently being stingy with adding more user settings for this very reason.

**Comment by ObadaS** [comment] 2016-07-22 12:41
Okay then, I hope at least that if colors are not implemented, the **bold** option is. Thank you for taking the time to respond.

Have a nice day !

**Comment by ccrama** [comment] 2016-08-01 13:26
The issue is the subreddit names are already bold when they are colored, and personally I think it looks a bit strange to have it bold as it's already in the first position of the info line and very easy to spot. I think I will close this for now, if you have any other suggestions to this feature let me know

**Closed by ccrama** 2016-08-01 13:26 UTC
Labels: feature request
