### ISSUE TITLE
Slide crashes after hiding last post

### ISSUE THREAD

**Issue by 2fst4u** [ccrama/Slide#1129] opened 2016-03-02 02:58 UTC
Slide version: 4.6.1-25-a6cb3ac
Android version:6.0.1

When hiding the last post in a sub by using the individual hide buttons, whether subscribed to the sub or not, slide crashes and restarts.

**Comment by Alexendoo** [comment] 2016-03-05 20:58
Can't reproduce this on latest, may have been fixed

**Comment by 2fst4u** [comment] 2016-03-27 03:16
Not fixed. In version 5 this still occurs.

**Comment by Alexendoo** [comment] 2016-03-27 13:37
```
E/AndroidRuntime(10245): FATAL EXCEPTION: main
E/AndroidRuntime(10245): Process: me.ccrama.redditslide.debug, PID: 10245
E/AndroidRuntime(10245): java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{305bcc44 position=0 id=-1, oldPos=0, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
E/AndroidRuntime(10245):        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4487)
E/AndroidRuntime(10245):        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4618)
E/AndroidRuntime(10245):        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4599)
E/AndroidRuntime(10245):        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988)
E/AndroidRuntime(10245):        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384)
E/AndroidRuntime(10245):        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347)
E/AndroidRuntime(10245):        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
E/AndroidRuntime(10245):        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:2954)
E/AndroidRuntime(10245):        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2879)
E/AndroidRuntime(10245):        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3265)
E/AndroidRuntime(10245):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(10245):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(10245):        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:596)
E/AndroidRuntime(10245):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(10245):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(10245):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(10245):        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(10245):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(10245):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(10245):        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1187)
E/AndroidRuntime(10245):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(10245):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(10245):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(10245):        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(10245):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(10245):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(10245):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime(10245):        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime(10245):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime(10245):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(10245):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(10245):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(10245):        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(10245):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(10245):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(10245):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime(10245):        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime(10245):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime(10245):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(10245):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(10245):        at me.ccrama.redditslide.SwipeLayout.SwipeBackLayout.onLayout(SwipeBackLayout.java:393)
E/AndroidRuntime(10245):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(10245):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(10245):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(10245):        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(10245):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(10245):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(10245):        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
E/AndroidRuntime(10245):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
E/AndroidRuntime(10245):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime(10245):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
E/AndroidRuntime(10245):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(10245):        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(10245):        at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime(10245):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(10245):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(10245):        at android.os.Handler.dispatchMessage(Handler.
```

**Comment by ccrama** [comment] 2016-04-09 19:51
Should no longer be an issue

**Comment by 2fst4u** [comment] 2016-04-10 02:45
Still happens on latest Google play update. 5.1.1

**Comment by Alexendoo** [comment] 2016-04-10 08:39
@2fst4u the latest version is 5.1.3, is it still happening there?

**Comment by Controless** [comment] 2016-04-10 08:44
@Alexendoo Can confirm, happening to me too on the latest version.

**Comment by 2fst4u** [comment] 2016-04-10 08:45
Yup, just got two updates in one day. Still happening on 5.1.3

**Comment by Alexendoo** [comment] 2016-04-10 09:01
Okay thanks, I haven't managed to get this one happening recently, what subs are you looking at? Sort mode, number of posts, anything you can think of

**Comment by 2fst4u** [comment] 2016-04-10 19:04
It was previously happening in every combination of sub and sort. I just
tried again and it worked without crashing though. Might need to check with
other users though

**Comment by ccrama** [comment] 2016-04-15 05:11
Should be fixed now

**Closed by ccrama** 2016-04-15 05:11 UTC
Labels: crash, needs reproduction
