### ISSUE TITLE
Shadowbox button glitches in offline mode and doesn't display anything

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1483] opened 2016-04-20 07:11 UTC
Slide version: 5.2.5
Android version: 6.0.1

After I click the shadowbox button, nothing happens and I'm unable to click anything else. The only action I'm able to perform is swipe right, which exits the shadowbox mode.

**Comment by ccrama** [comment] 2016-04-20 14:07
Can't reproduce

**Comment by ccrama** [comment] 2016-04-21 15:23
Users that had this said it's fixed in the latest alpha

**Closed by ccrama** 2016-04-21 15:23 UTC
Labels: bug, needs reproduction
