### ISSUE TITLE
The Mark As Read button does not dismiss the inbox notifications if the post has already been read.

### ISSUE THREAD

**Issue by krompus** [ccrama/Slide#2309] opened 2016-11-30 18:44 UTC
Slide version: 5.5.2
Android version: 6.0.1

Tiny bug, but it would be nice to squash it. :)

**Comment by ccrama** [comment] 2016-11-30 18:57
Inbox notifications are tied to comments and not posts, that is the intended behavior if I'm understanding you correctly

**Comment by krompus** [comment] 2016-11-30 18:59
Yes; I meant to say "if the comment has been read".

**Comment by ccrama** [comment] 2016-11-30 19:01
That is just how Reddit works, you can view a comment but it will still be in your inbox

**Comment by krompus** [comment] 2016-11-30 19:06
The notification itself does not get dismissed if you click "Mark as Read" when the post has already been read.

Perhaps I have misunderstood how the notification functions; I thought that it would dismiss the notification when you click Mark as Read. Testing.

**Comment by krompus** [comment] 2016-11-30 23:42
Bug confirmed.

When the user taps the Mark as Read button on the New Messages notification, and the messages in question have not been read, it dismisses the notification, and marks the posts as read. This is functioning correctly / as intended.

When the user taps the Mark as Read button on the New Messages notification, and the messages in question *have* been read, the notification is not dismissed.

It seems to me that the notification should be dismissed when you tap "Mark as read", regardless of whether the notifications have been read or not.

Of course, the workaround is very simple; just swipe the notification to the side to dismiss it when the Mark as Read tap fails to dismiss the notification.

**Comment by ccrama** [comment] 2016-12-11 19:51
Ah gotcha now. Should be fixed for the next update after 5.5.3!

**Closed by ccrama** 2016-12-11 19:51 UTC
