### ISSUE TITLE
Slide consistently crashes on certain image loads

### ISSUE THREAD

**Issue by bantar** [ccrama/Slide#1274] opened 2016-03-28 18:55 UTC
Slide version: 5.0.1
Android version: 5.0

I've found multiple images that are instant crashes.   Click on the link and it crashes.  

https://www.reddit.com/r/MechanicAdvice/comments/4b1zf4/2005_acura_tsx_transmission_vent_tube_cap/  
The OP has a link "Picture of aforementioned vent tube." which is http://imgur.com/KxMrQ5j   I see that this link does not have a filetype.

I thought that I had saved 2 examples, however, the 2nd example is now working.   I've seen others, but I just saved a few for reporting.  I'll have to find a more examples if needed.

**Comment by ccrama** [comment] 2016-03-28 19:03
Working fine for me, no crashes. It's a huge image though, so I'm pretty sure your phone is running out of RAM trying to show it

**Comment by bantar** [comment] 2016-03-28 19:50
Using Now for Reddit, it loads just fine.   However, it could be scaling where Slide is not.  This image is only 463KB, it's not large by memory standards.   Here's a bigger image that I can load just fine and then proceed to the smaller one to cause the instant crash:  https://www.reddit.com/r/MechanicAdvice/comments/4c89sr/please_help_me_figure_out_what_this_is_its/

Well, what do you know.   The original image posted here is no longer insta-crashing.   It is now refusing to load.   Just have the overlay with no image.  

Somehow, this problem does appear to be related to resources as it's not failing now.   When it failed, it consistently failed 3 times in a row.   Each one was confirmed to be a repeatable failure.  The S5 has 1.66 GB of RAM for use.  The only thing that I can tell you about RAM usage is that normally, I'm quite focused.  When using reddit, it's only reddit for a long while.  I don't bounce around much.

**Comment by ccrama** [comment] 2016-03-28 19:54
Well I can't reproduce or make it crash on any of my 4 devices. In fact, I've never had it crash or not load an image before

**Comment by bantar** [comment] 2016-03-28 20:00
Do the crash reports come to you when we submit them.   I've recently submitted a few that say imgur.com image load as the failure report reason.

**Comment by ccrama** [comment] 2016-03-28 20:17
Almost all are OOM errors, we have very few other actual bug errors

**Comment by bantar** [comment] 2016-03-28 20:27
Interesting.  The memory usage on my phone should be 100% related to reddit operations.  Yet, after Slide crashes, the failure is reproducible again and again.   Yet, I can continue to browse and not have problems with many other messages.    I saved these images many hours before reporting them.  Clearly after a bit of garbage collection, I'm seeing better behavior.   

Unless you see any value here, we can go ahead and close this bug report.

**Comment by InfinityMeep** [comment] 2016-04-03 19:32
I also have this issue, but crashes also occur sometimes when loading subreddits.  Like OP, I have an S5, but mine is on 5.1.1.  It seems to crash after using the app for a while.  I'll see if I can find any patterns in the crashes

**Comment by bantar** [comment] 2016-04-04 15:14
Slide crashes for me 5-10 times daily.   Mostly when clicking on images.  Almost always within a minute or two after resuming from background.    Mostly, I'd guess that I make it thru 50 messages between crashes.   I have found absolutely no pattern to the crashes.    After it restarts, the same click on image crash works.    I report all crashes.

I never report a failure unless I can reliably recreate the failure many times.  The original images initially reported no longer fail for me.  Now, all crashes are completely random.  I think it's more due to time and usage (possibly until all memory is exhausted).  Then is crashes and works fine again.

**Comment by bantar** [comment] 2016-04-04 15:16
@InfinityMeep  Since you also have an S5, can you try to create the failures shown in #1196 and report your findings?    Scroll to the bottom of that long thread and try one of the later sets of steps to recreate.

**Comment by ccrama** [comment] 2016-04-04 19:08
@bantar  almost 100% certainly out of memory errors (almost all of the crashes reported are OOM errors). Really don't know what I can do

**Comment by bantar** [comment] 2016-04-04 19:23
I don't doubt it's memory.   However, it appears to be specific to the app.   I can move over to a different reddit client and never crash doing the same boring content reading and picture viewing.   I'd question what objects are lingering in memory that readily clears up when the app crashes?    If you had any suggestions for how I might monitor memory usage to find a pattern, I'd give it a shot.    On the surface, there is no discernible pattern.

**Comment by ccrama** [comment] 2016-04-04 19:24
Turn on low quality mode in settings, does that fix it? That does essentially what the other apps do by default

**Comment by Alexendoo** [comment] 2016-04-04 19:33
Isn't it only sync that loads low quality by default? The few I tried use webview or zoom properly.

The cause of the crash might say OOM but it doesn't sound like something that's happening organically

**Comment by bantar** [comment] 2016-04-04 19:47
I'll give low quality a run and report back.   I've made the change, appears to work, but it'll be a while before I can browse.

The cause of the crash, to me, is a mystery.  It just crashes with no message or reason.   I can't tell why I'm crashing.  I can tell you that upon crash, I immediately scroll back to that position and hit the same message again.  The image loads right up.  The only memory that gets freed should be that of the crashing app (since I immediately restart and don't go do other things).

**Comment by ccrama** [comment] 2016-04-04 20:24
It will run out of memory randomly, there doesn't have to be a pattern if it's an OOM

**Comment by bantar** [comment] 2016-04-04 20:42
It could be a specific action that consumes the memory and does not free it.  It would be hard to spot for sure.   For instance, an imgur album, or a dip into youtube.   But, if you think I'm wasting my time, I'll let it go.  Just offering to watch for it.   When I pop out to check my device memory consumption, it always appears to be relatively static - very little movement up or down.

**Comment by ccrama** [comment] 2016-04-04 20:44
It's almost certainly just loading a bitmap, which has a huge memory footprint. I'm glad you're reporting it, just wish there was a surefire fix. The only thing I can do is tweak it little bits and see if that makes any impact on crash reports. 90% of the reports I've gotten are from loading images, so it's definitely a RAM issue. More than 15% (pretty large margin) are Galaxy S5's, so hoping it's not a device issue :(

**Comment by ccrama** [comment] 2016-04-04 21:05
Trial fix will be in the v5.0.4 update, let me know if this fixes anything

**Comment by bantar** [comment] 2016-04-04 22:10
OK, under Data Saving, I changed Load Low Quality Images to:  Mobile Data and WiFi.  Then, I checked the box under it that says Load lower quality image if possible.    I browsed thru about 30 messages and just crashed again on an image load (an imgur link in the comments of a message).   Went right back and it crashed again.   Went right back and clicked different image, then the failing one and it worked just fine.  

I'll let you know if 5.0.4 helps.   Thanks for trying!

**Comment by bantar** [comment] 2016-04-05 01:25
I just joined the Alpha today.  It says "You are a tester"  Yet, I don't see 5.0.4 on the Google Play.   Let me know what it takes to get approved and I'll give it a whirl.

**Comment by l3d00m** [comment] 2016-04-05 05:28
I think you have to wait a longer time.

**Comment by bantar** [comment] 2016-04-07 01:40
I had to Leave the Alpha Test and rejoin.  I finally got 5.0.4 to download a few hours ago.    

At this point, I think you've nailed this problem.   I've been trying to break it, but so far not.  It should have crashed 3-4 times by now.    I'll give it a bit more testing and if all looks good, we can put a bow on this one.    Thanks!

**Comment by ccrama** [comment] 2016-04-07 03:19
Glad to hear it :D! I think it's fixed too, have done a lot of testing (could reproduce some on my Nexus 5). Feel free to re-open this if you get more issues!

**Closed by ccrama** 2016-04-07 03:19 UTC
Labels: bug, needs reproduction

**Comment by bantar** [comment] 2016-04-07 15:19
Indeed, I do now consider this fixed.   I see a remnant that I'll open a new issue for.
