### ISSUE TITLE
Switching accounts - previous account is still logged in

### ISSUE THREAD

**Issue by MustardCat** [ccrama/Slide#2518] opened 2017-08-25 02:50 UTC
Slide version: 5.6.5.1-alpha4
Android version: 8.0

Copying [the post from reddit](https://www.reddit.com/r/slideforreddit/comments/6vh7ja/bug_just_updated_to_android_o_now_i_cannot_switch/) as it was written pretty well: 

> When I switch accounts it shows the correct username but it shows submitted history from a different account and submissions are posted from that account instead of the correct one. Case and point I'm signed in to my main account but this will be posted through my throwaway.

I'm able to switch to Guest and then switch to the account I want to post from (as a temp fix) but another user posted saying this didn't work for them

**Comment by ccrama** [comment] 2017-08-26 15:52
I think this is somehow related to Android O, as I could not reproduce this on N

**Comment by MustardCat** [comment] 2017-08-26 16:48
Yeah, it's definitely something with Android O.  The issue wasn't there on N or on my tablet (which is running M).

Since you're not running O on your Pixel, I guess this issue will have to be sidelined until it's actually being pushed out to the non-beta users (which might be a while since there's a big bluetooth issue in the final build)

**Comment by ccrama** [comment] 2017-08-26 17:23
I am now running O on my Pixel (my daily is sadly an iPhone 6s right now). I'll look into it! Want to fix this before release

**Comment by Schmitty623** [comment] 2017-08-30 00:52
Experiencing all the same issues described above with Oreo. I should also note that while I see the subreddits for my second account listed along the top of the screen when using that account, the Frontpage is pulling from my primary account and showing what I would normally see with that account's subreddits.

**Comment by ccrama** [comment] 2017-09-21 00:02
Fixed! Was an issue with Java 1.8 and not something in Slide, but I found a workaround to make it work. It was failing and moving to my redundant error code, which defaulted to keeping the same user logged in.

**Closed by ccrama** 2017-09-21 00:02 UTC
