### ISSUE TITLE
Submitting a post crashes the app

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#146] opened 2015-10-18 13:30 UTC
1. Open submit post via left sidebar. 
2. Submit a self post to /r/test
3. App crashes, but the post is successfully posted

I cannot copy a Stacktrace because the app crashes directly and doesn't show the slide has crashed activity.

**Comment by ccrama** [comment] 2015-10-18 13:41
Dupe of #124

**Closed by ccrama** 2015-10-18 13:41 UTC
