### ISSUE TITLE
You have to manually restart Slide after adding an account

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#853] opened 2016-01-21 07:43 UTC
A little dialog says [Adding account] and that Slide will restart, but it doesn't.

You can wait forever, but nothing will happen.

You have to restart Slide manually for the changes (new account, new subreddits list) to take effect.

**Comment by ccrama** [comment] 2016-01-22 19:15
It restarts perfectly for me, cannot reproduce

**Comment by alexsmithfanning** [comment] 2016-01-22 19:52
I have to wait about ten to fifteen seconds for mine to restart. That could be my phone though.

**Comment by okungnyo** [comment] 2016-01-22 21:35
@ccrama, try these steps and see if you can reproduce:

1. Have your main account (/u/ccrama, or whatever it is) added.
2. Make a new throwaway on reddit.com that you've never used before to sign into Slide. It **must** be a **completely** new throwaway.
3. Sign into Slide with it. Post results.

**Comment by l3d00m** [comment] 2016-01-31 17:41
Can't reproduce it either with a completely new throwaway. It just needs a few seonds in the log into reddit screen

**Comment by ccrama** [comment] 2016-02-06 16:09
I did and it works fine, restarts and brings me to the new account @okungnyo

**Comment by ccrama** [comment] 2016-02-06 16:09
I'm gonna merge this with #854

**Comment by Alexendoo** [comment] 2016-02-18 17:31
Should be fixed with cfbad2f1bd1e9dbae5777bd67f115c1876f60f88

**Closed by Alexendoo** 2016-02-18 17:31 UTC
Labels: bug, needs reproduction
