### ISSUE TITLE
I don't know how this was triggered

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#253] opened 2015-10-25 03:55 UTC
I hope this helps.

Debug info:
 OS Version: 3.10.40-perf-g90ddf4a(44)
 OS API Level: 22
 Device: quark
 Model (and Product): XT1254 (quark_verizon)
 RELEASE: 5.1
 BRAND: motorola
 DISPLAY: SU4TL-44
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: motorola

Stacktrace: 

```java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.Profile}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
	at android.app.ActivityThread.access$800(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5356)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at me.ccrama.redditslide.Activities.Profile.onCreate(Profile.java:57)
	at android.app.Activity.performCreate(Activity.java:6010)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
	... 10 more
```

**Comment by l3d00m** [comment] 2015-10-25 07:06
Dupe of #250

**Closed** 2015-10-25 12:56 UTC
