### ISSUE TITLE
Refreshing when directly linked to a comment causes a crash

### ISSUE THREAD

**Issue by dedChar** [ccrama/Slide#18] opened 2015-10-08 19:52 UTC
Title

**Comment by Alexendoo** [comment] 2015-10-08 21:16
@dedChar Viewing a reply of what exactly?

**Comment by dedChar** [comment] 2015-10-09 04:45
Viewing a reply to your comment. When you open it through inbox it opens up the post with only you comment and its replies loaded. Trying to refresh the post here crashes slide.

**Comment by ccrama** [comment] 2015-10-09 13:36
Could not reproduce. Are you on the latest version of Slide?

**Comment by Alexendoo** [comment] 2015-10-11 11:46
Good news! (bad news?) managed to reproduce it, for now here's the log I will look into it a little more also. https://gist.github.com/Alexendoo/2cd105528e8c69dab270

**Comment by Alexendoo** [comment] 2015-10-12 00:02
It appears refreshing when viewing a comment linked directly is the cause of this crash.

http://www.reddit.com/r/Android/comments/3ocsz2/baconreader_for_reddit_50_includes_material/cvw4vpy

**Comment by ccrama** [comment] 2015-10-12 03:15
Fixed with 85fb67c73a8fb0d4d3aea2da27ddc44867924ca4! Tested on inbox, intent, and reddit URL from in app.

**Closed by ccrama** 2015-10-12 03:15 UTC
Labels: bug, crash
