### ISSUE TITLE
Unfolding a comment crashes the app

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#63] opened 2015-10-13 19:10 UTC
Android 5.0.2 LG G2 using v4.0.5

**Comment by Alexendoo** [comment] 2015-10-13 19:43
Possible duplicate of #7, what version are you running?

**Comment by Alexendoo** [comment] 2015-10-13 19:47
If you're not already on it would you please test if the issue still occurs for you with https://www.filepicker.io/api/file/Xy3b6VtQQ7q6JY0vFbnv

**Comment by l3d00m** [comment] 2015-10-13 19:48
I'm running the newest? v4.0.5, #7 was more about single clicks and it was random. This one happens when double tapping a comment fast. I can close it and comment under #7, though.

**Comment by l3d00m** [comment] 2015-10-13 19:53
It's always happening when you're unfold the comment, not matter how fast. Should I add it to #7?

**Comment by Alexendoo** [comment] 2015-10-13 19:54
@l3d00m No I was mistaken it doesn't appear to be a duplicate, did you try on the linked file? It's newer than alpha5

**Comment by l3d00m** [comment] 2015-10-13 20:02
Sorry that I overread your answer, I need more coffee :p  
I have downloaded the apk through your link and it still says  v4.0.5 and it still crashes when unfolding a comment. (LG g2, Android 5.0.2)

**Comment by ccrama** [comment] 2015-10-13 23:42
Fixed in latest version. Had an issue where I tried to pre-cache views that didn't exist! Fixing with 760d37d2b03039eb2f0413048a4378a70a308e38

**Closed by ccrama** 2015-10-13 23:42 UTC
Labels: bug, crash

**Comment by l3d00m** [comment] 2015-10-14 05:02
Thanks!
