### ISSUE TITLE
Slide doesn't open external links with default app

### ISSUE THREAD

**Issue by hdmi** [ccrama/Slide#2095] opened 2016-08-28 22:14 UTC
Slide version: v5.4.2.3
Android version: Android 7.0 (stock)
Device: Nexus 6P

Every time I click a twitter link with slide It directly opened with the inbuilt web browser, not the default twitter app (Flamingo in my case). i clicked the option, always open this link externally but it seems to do nothing.

Here is a video of ths problem https://youtu.be/EEa-DYSkn2I

**Comment by Nxt3** [comment] 2016-08-28 23:32
I've had this happen from time to time; not sure if it's Slide's fault though.

**Comment by freundTech** [comment] 2016-08-29 07:18
Can you go to settings->Link handling and check if twitter.com was added to the "Force external browser" list, so we know if it's a problem with the "Always open external" button or the feature itself?

**Comment by hdmi** [comment] 2016-08-29 07:39
@freundTech Yes, this step has solved my problem.

Here is a screenshot of the Link handling list before:
http://i.imgur.com/aIwMXv3.png

Then after adding twitter.com to the list, the links started opening in the default twitter client
http://i.imgur.com/r4KHb1L.png

So the problem that I see here is that Slide for reddit is not handling the subdomains as it should, imo "mobile.twitter.com" should inherit the "twitter.com" domain too.
By the way, Slide also spams to the link handling list the URLs that are already there.

Thanks for the support :)

**Comment by freundTech** [comment] 2016-08-29 07:44
Oh. I think the problem is that the button adds the currently opened website (mobile.twitter.com) to the list, while the actual link goes to twitter.com, which isn't on the list.

Twitter.com then redirects you to mobile.twitter.com, but at that point the internal browser is already opened, so slide doesn't check again if it should open the link externally.

**Comment by ccrama** [comment] 2016-08-29 18:04
I think all we need to do to solve that is only store the "twitter.com" part instead of subdomains, would there be a situation where subdomains are actually used?

**Comment by freundTech** [comment] 2016-08-29 18:08
Yes, with websites like wordpress (username.wordpress.com), github pages (username.github.io) and similar services that give you free webhosting/subdomains.

**Comment by ccrama** [comment] 2016-08-29 18:32
Merged your PR which should fix this issue, thank you!

**Closed by ccrama** 2016-08-29 18:32 UTC
Labels: bug
