### ISSUE TITLE
Comments get mixed up on collapse

### ISSUE THREAD

**Issue by prashantkhurana** [ccrama/Slide#1933] opened 2016-07-17 19:25 UTC
I am noticing this behavior  : 
https://www.youtube.com/watch?v=K74kIK-X0vg

**Comment by ccrama** [comment] 2016-07-18 14:10
I have never run into this, might just be something on your branch

**Comment by prashantkhurana** [comment] 2016-07-18 14:27
I am not sure which version it is, let me try on the latest alpha.

**Comment by prashantkhurana** [comment] 2016-07-18 15:03
you can close it for now. If this happens again, I'll make a new issue with a way to reproduce it. Thanks.

**Comment by azertyfun** [comment] 2016-07-29 16:09
The bug occurs when a comment is collapsed while a child comment chain is still loading (caused by hitting the "Load `n` more" button). When the child finally loads, it displays when it shouldn't - since the parent comment is collapsed. It is consistent, as long as you can collapse the comment quickly enough.

https://www.youtube.com/watch?v=lvJYuArLvRc

**Comment by ccrama** [comment] 2016-08-06 19:11
Should be fixed now. Good find!

**Closed by ccrama** 2016-08-06 19:11 UTC
Labels: bug

**Comment by prashantkhurana** [comment] 2016-08-07 21:42
Still happening. Unfortunately cannot provide more context, but lets keep it open. I am looking into it.

**Comment by ccrama** [comment] 2016-08-07 21:47
It's looks like a different issue then, I for sure fixed the loading more
issue

**Comment by prashantkhurana** [comment] 2016-08-07 21:49
yeah, has to be. I asked to keep this open as the outcome is the same " Comments get mixed up on collapse". I have a concrete example now in offline mode. So hopefully will be able to find out why this is happening.

**Comment by prashantkhurana** [comment] 2016-08-07 23:09
found the issue (only for offline mode) : we don't display "load more comments" and use more child stuff.but all the calculations (example getChildNumber()) uses it, so it messes up everything.

**Comment by l3d00m** [comment] 2016-08-08 18:54
@prashantkhurana May you open a new issue for that (if it isn't fixed already)?

**Comment by prashantkhurana** [comment] 2016-08-08 20:22
yeah, did that.
