### ISSUE TITLE
I tried to share an image and the app suddenly crashed. 

### ISSUE THREAD

**Issue by Zelath** [ccrama/Slide#236] opened 2015-10-22 22:58 UTC
## Info
Click on an image and press the share button 
## Stacktrace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
at me.ccrama.redditslide.Activities.FullscreenImage.saveImageLocally(FullscreenImage.java:228)
at me.ccrama.redditslide.Activities.FullscreenImage.access$000(FullscreenImage.java:36)
at me.ccrama.redditslide.Activities.FullscreenImage$4$1.onLoadingComplete(FullscreenImage.java:109)
at com.nostra13.universalimageloader.core.DisplayBitmapTask.run(DisplayBitmapTask.java:72)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
Slide v4.2.1, API v23
Reported via Slide Crash Capture

**Comment by l3d00m** [comment] 2015-10-23 09:59
dupe of #230?

**Comment by ccrama** [comment] 2015-10-23 13:12
Yep

**Closed by ccrama** 2015-10-23 13:12 UTC
