### ISSUE TITLE
Save screen when switching apps

### ISSUE THREAD

**Issue by catzs** [ccrama/Slide#2479] opened 2017-07-05 08:16 UTC
When I switch apps to copy something, the Slide app stays on the thread, but when you back out, it will reset to the front page

**Comment by Nxt3** [comment] 2017-07-05 12:35
Not sure I understand the issue. If you back out of the app, you're effectively closing it. This is the intended behavior.

**Comment by Nxt3** [comment] 2017-09-28 19:56
Closing this since no more information is given.

**Closed by Nxt3** 2017-09-28 19:56 UTC
