### ISSUE TITLE
crashes when trying to share image. 

### ISSUE THREAD

**Issue by Dowenprs** [ccrama/Slide#181] opened 2015-10-20 02:58 UTC
## Info
Try to share image from tattoo sub
## Stacktrace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsoluteP
ath()' on a null object reference
at me.ccrama.redditslide.Activities.FullscreenImage.saveImageLocally(FullscreenImage.java:228)
at me.ccrama.redditslide.Activities.FullscreenImage.access$000(FullscreenImage.java:36)
at me.ccrama.redditslide.Activities.FullscreenImage$4$1.onLoadingComplete(FullscreenImage.java:109)
at com.nostra13.universalimageloader.core.DisplayBitmapTask.run(DisplayBitmapTask.java:72)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.disp
atchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(N
ative Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
Reported via Slide Crash Capture

**Comment by l3d00m** [comment] 2015-10-20 06:35
Which version are you using?

**Comment by ccrama** [comment] 2015-10-20 12:44
Seems to be from an old version, this was fixed for the current version!

**Comment by ccrama** [comment] 2015-10-23 13:29
Dupe of #230

**Closed by ccrama** 2015-10-23 13:29 UTC
Labels: autoreport

**Comment by smccjj** [comment] 2017-09-18 07:53
good
