### ISSUE TITLE
Markdown: Strikethrough

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#122] opened 2015-10-17 15:59 UTC
The Markdown for strikethrough (``~~text~~``) doesn't seem to be rendered properly.

I used the following Markdown to test.

```markdown
~~text~~

**~~Bold text~~**

~~**text Bold**~~

*~~Italic text~~*

~~*text Italic*~~

***~~Bold Italic text~~***

Text ~~^Superscript~~

Text ~~^Strikethrough~~

[~~text~~](https://encrypted.google.com)

~~[text](https://encrypted.google.com)~~

##Lists
1. Item 1
2. ~~Item 2~~
3. ***~~Item 3~~***

##More lists
* Item 1
* ~~Item 2~~
* Item 3
```

**Comment by ccrama** [comment] 2015-10-17 16:52
Interesting find! Will work on this

**Comment by ccrama** [comment] 2015-10-19 22:08
Took me a while to figure this one out. Turns out reddit returns <del>, which TextView doesn't support, and not <strike>, which TextView supports

Fixed with 7220d0ecc61ae0ebbcea483f5ebef30e833fd922

**Comment by karlding** [comment] 2015-11-17 18:55
This seems to be broken again.

**Comment by Snagg57** [comment] 2015-11-17 19:01
Confirmed, on latest Slide 4.3.2 Playstore APK

Normal Reddit
http://i.imgur.com/DU235bL.png
Slide for Reddit
http://i.imgur.com/W6PDu6q.png

**Closed** 2016-02-14 00:28 UTC
Labels: bug, cosmetic
