### ISSUE TITLE
Opening a post linked in a PM will not mark it as read.

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#959] opened 2016-02-05 07:20 UTC
If you are having a hard time reproducing this, I can post screencaps.

Latest beta from Google play, Android 6.0

**Comment by ccrama** [comment] 2016-02-05 21:53
So if you click on a URL in a PM, it won't mark as read? That is the intended behavior if I understand you correctly.

**Comment by SZE2** [comment] 2016-02-05 22:12
If you open a Reddit link (e.g. To a ask Reddit discussion), it will not show that discussion as read in the regular sub list view later.

I'll upload screencaps after the weekend hopefully.

**Comment by ccrama** [comment] 2016-02-05 22:21
Oh, I understand. That's strange, it should definitely be marking as read. Will look into it

**Comment by ccrama** [comment] 2016-04-09 19:53
Has been fixed for a while, actually!

**Closed by ccrama** 2016-04-09 19:53 UTC
Labels: cosmetic, priority: low
