### ISSUE TITLE
Long subreddit names causes wrapping in card

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#689] opened 2015-12-01 04:56 UTC
Long subreddit names (and possibly long usernames) cause the card text to wrap, which looks really weird. The current design of the cards makes wrapping inevitable since the subreddit name and username are both on the same line.

For example, /r/wheredidthesodago.
![/r/wheredidthesodago](http://i.imgur.com/LLs48wA.png)

**Comment by Controless** [comment] 2015-12-01 05:08
Pretty sure this is a duplicate of another issue, I just can't find it atm.

**Comment by l3d00m** [comment] 2016-01-05 20:34
Fixed with 558e3b6ea9b2b491e4a6b1880de53767476223bf

**Closed by l3d00m** 2016-01-05 20:34 UTC
Labels: bug, cosmetic
