### ISSUE TITLE
"Share link" option from custom tabs

### ISSUE THREAD

**Issue by KaliK0t** [ccrama/Slide#314] opened 2015-11-01 02:34 UTC
~~Please ask whether user would like to share content or the link.~~

And chrome custom tab doesnt have share too.

Image link sharing only saves then uploads the photo instead of linking it

**Comment by ccrama** [comment] 2015-11-06 19:49
Done a few commits back

**Comment by Alexendoo** [comment] 2015-11-07 13:05
Custom tabs are still missing the share button

**Comment by l3d00m** [comment] 2015-11-18 18:00
dupe of #186

**Closed by l3d00m** 2015-11-18 18:00 UTC
Labels: enhancement
