### ISSUE TITLE
Saved posts follow default sorting time limits

### ISSUE THREAD

**Issue by IshyTheLegit** [ccrama/Slide#2525] opened 2017-09-10 12:09 UTC
Slide version: Slide v5.6.5.1-alpha4
Android version: 7.0
I can't see all of my saved posts.
E.g. Only posts saved during the last 24 hours are available when default sorting is Top>24 hours in settings

**Comment by ccrama** [comment] 2017-09-12 19:40
Hmm interesting find, I cannot reproduce this on desktop or by executing the API request myself. Are you sure changing the time period fixes that behavior on your device?

**Comment by ccrama** [comment] 2017-09-20 23:56
Closing for now, as this doesn't seem possible in the Reddit API. If you can confirm it is still occurring or run into another issue, feel free to re-open it!

**Closed by ccrama** 2017-09-20 23:56 UTC
