### ISSUE TITLE
Issue/crash with opening profile

### ISSUE THREAD

**Issue by pdejan** [ccrama/Slide#52] opened 2015-10-12 13:39 UTC
Last few vesrions I'm encountering this this issue where after I log in and everything is synced I cannot access my profile. When I open it, after few seconds I would get error "Unfortunatelly Slide has stoped" and app would log me out. After that I would fully close app and when relaunched everything would go back to normal where I'm loged in again. I cannot submit crash report because its technically not a crash? Also worth nothing is that I can access inbox just fine.
Using Nexus 5 on Android 6.

**Comment by Alexendoo** [comment] 2015-10-12 14:33
Slide has stopped would be a crash but I cannot reproduce this myself

**Comment by ccrama** [comment] 2015-10-12 17:40
Cannot reproduce, unfortunately. Do you run into this issue with other clients? Does it do this with a different account?

**Comment by pdejan** [comment] 2015-10-12 18:19
Nope, not really used any other reddit client extensively. And this only started happening after this latest rewrite of client. (When you released first alpha few days ago and following all recent updates. I didn't report it immediately because I though maybe not all features are implemented.) Don't have any other reddit accounts to test and don't feel like making them either, sorry about that. 
Also worth noting is I'm using Android 6, not that it should change anything really since its not that much different from 5.
Here's a video if that can even help with anything. (I did clean install every time you released new updated just to remove option of some issues during updates).
https://goo.gl/photos/aJyEwEiFkAppQa7T8

**Comment by ccrama** [comment] 2015-10-12 22:08
Your profile crashes my app too! Was able to replicate and fix. Will close when I push the commit

**Comment by pdejan** [comment] 2015-10-12 22:30
Glad to hear!

**Comment by ccrama** [comment] 2015-10-12 22:32
Fixed with 7f3bae7e1f26aa7f2d17754a9d864bdf8266860f! You can grab the fixed APK on the G+ page

**Closed by ccrama** 2015-10-12 22:32 UTC
Labels: bug, crash, needs verification
