### ISSUE TITLE
Vertical scrolling is a struggle because of a "Swipe away"

### ISSUE THREAD

**Issue by benjamindean** [ccrama/Slide#1335] opened 2016-04-08 07:14 UTC
Slide version: 5.1.1
Android version: 6.0.1

For example, vertical scrolling in Settings activity feels almost impossible because of horizontal scrolling which takes you back all the time. The same goes for vertically aligned albums. I remember there was a "Swipe away" option some time ago. Is it turned on by default now?

**Comment by Alexendoo** [comment] 2016-04-08 11:22
Related #1283

**Comment by The0x539** [comment] 2016-04-09 21:36
Arguably a duplicate of #957...?

**Comment by benjamindean** [comment] 2016-04-10 06:50
@The0x539 Yep, but this one was closed 12 days ago. Looks like it was fixed for some of the views, but not all of them.

**Comment by ccrama** [comment] 2016-04-27 20:09
Done now!

**Closed by ccrama** 2016-04-27 20:09 UTC
Labels: feedback
