### ISSUE TITLE
Clicking on a subreddit link before the comments finished loading crashes slide

### ISSUE THREAD

**Issue by KaliK0t** [ccrama/Slide#140] opened 2015-10-18 06:30 UTC
Welp

**Comment by ccrama** [comment] 2015-10-18 13:37
What do you mean a "subreddit link"?

**Comment by ccrama** [comment] 2015-10-18 13:37
Sorry, didnt mean to close.

**Comment by KaliK0t** [comment] 2015-10-18 13:40
If a subreddit is linked in the OP it crashes on click before comments are
loaded

**Comment by ccrama** [comment] 2015-10-18 13:51
Cannot reproduce

**Comment by KaliK0t** [comment] 2015-10-18 13:56
I encountered it with the reddit CEO ama post yesterday. He linked
r/alienblue (i know...) and it crashed when i clicked

**Comment by Alexendoo** [comment] 2015-10-24 08:22
Appears to have been #240

**Comment by Alexendoo** [comment] 2015-10-24 23:29
Closing as the other issue has more information

**Closed by Alexendoo** 2015-10-24 23:29 UTC
Labels: bug, crash
